#!/bin/bash

DEMO_DIR="$( dirname "${BASH_SOURCE[0]}" )"
. ${DEMO_DIR}/demo-magic

ROOT_DIR="$( cd ${DEMO_DIR}/../.. && pwd)"
CLUSTERS_DIR=${CLUSTERS_DIR:-${DEMO_DIR}/clusters/kind}

TYPE_SPEED=30
#PROMPT_AFTER=1
DEMO_PROMPT="☸️ $ "

function pause() {
  if [[ -n "${NO_WAIT}" ]]; then
    sleep 2
  else
    if [[ -n "${1-}" ]]; then
      sleep "$1"
    else
      wait
    fi
  fi
}

export KUBECONFIG=${ROOT_DIR}/.kcp/data/admin.kubeconfig
if ! kubectl get namespaces &>/dev/null; then
  echo "kcp server not started, run 'bin/kcp start'"
fi

kubectl config use-context admin

clear

pe "kubectl api-resources | grep deployments"

pe "kubectl apply -f ${CLUSTERS_DIR}/us-east1.yaml"
pe "kubectl get clusters -o wide"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl patch negotiatedapiresources deployments.v1.apps --type=\"merge\" -p '{\"spec\":{\"publish\":true}}'"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl get crds -o wide  | grep deployments"
pe "kubectl api-resources | grep deployments"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl get crds deployments.apps -o yaml | grep ephemeralContainers"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl apply -f ${CLUSTERS_DIR}/us-west1.yaml"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get apiresourceimports deployments.us-west1.v1.apps -o=go-template='{{ range .status.conditions }}{{ if eq .type \"Compatible\" }}{{ .message }}{{ end }}{{ end }}'"
pe "kubectl patch apiresourceimports deployments.us-west1.v1.apps --type=\"merge\" -p '{\"spec\":{\"schemaUpdateStrategy\":\"UpdatePublished\"}}'"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresource deployments.v1.apps -o yaml | grep ephemeralContainers"
pe "kubectl get crds deployments.apps -o yaml | grep ephemeralContainers"
pe "kubectl delete clusters us-west1"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresource deployments.v1.apps -o yaml | grep ephemeralContainers"
pe "kubectl get crds deployments.apps -o yaml | grep ephemeralContainers"
pe "kubectl delete clusters us-east1"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl api-resources | grep deployments"

pause
clear

pe "kubectl apply -f ${ROOT_DIR}/contrib/crds/apps/apps_deployments.yaml"
pe "kubectl apply -f ${CLUSTERS_DIR}/us-west1.yaml"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl patch apiresourceimports deployments.us-west1.v1.apps --type=\"merge\" -p '{\"spec\":{\"schemaUpdateStrategy\":\"UpdatePublished\"}}'"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresources -o wide"
pe "kubectl apply -f ${CLUSTERS_DIR}/us-east1.yaml"
pe "kubectl get apiresourceimports -o wide"
pe "kubectl get negotiatedapiresources -o wide"

wait
