/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1beta1

import (
	kcpinternalinterfaces "github.com/kcp-dev/client-go/apiextensions/informers/internalinterfaces"
)

type ClusterInterface interface {
	// CustomResourceDefinitions returns a CustomResourceDefinitionClusterInformer.
	CustomResourceDefinitions() CustomResourceDefinitionClusterInformer
}

type version struct {
	factory          kcpinternalinterfaces.SharedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f kcpinternalinterfaces.SharedInformerFactory, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// CustomResourceDefinitions returns a CustomResourceDefinitionClusterInformer.
func (v *version) CustomResourceDefinitions() CustomResourceDefinitionClusterInformer {
	return &customResourceDefinitionClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
