/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	kcpworkloadv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/workload/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/workload/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
)

// ResourceImportsClusterGetter has a method to return a ResourceImportClusterInterface.
// A group's cluster client should implement this interface.
type ResourceImportsClusterGetter interface {
	ResourceImports() ResourceImportClusterInterface
}

// ResourceImportClusterInterface can operate on ResourceImports across all clusters,
// or scope down to one cluster and return a kcpv1alpha1.ResourceImportInterface.
type ResourceImportClusterInterface interface {
	Cluster(logicalcluster.Path) kcpv1alpha1.ResourceImportInterface
	List(ctx context.Context, opts v1.ListOptions) (*kcpworkloadv1alpha1.ResourceImportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ResourceImportClusterExpansion
}

type resourceImportsClusterInterface struct {
	clientCache kcpclient.Cache[*kcpv1alpha1.WorkloadV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *resourceImportsClusterInterface) Cluster(clusterPath logicalcluster.Path) kcpv1alpha1.ResourceImportInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).ResourceImports()
}

// List returns the entire collection of all ResourceImports across all clusters.
func (c *resourceImportsClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*kcpworkloadv1alpha1.ResourceImportList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceImports().List(ctx, opts)
}

// Watch begins to watch all ResourceImports across all clusters.
func (c *resourceImportsClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceImports().Watch(ctx, opts)
}
