/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kcp-dev/kcp/sdk/apis/core/v1alpha1"
	conditionsv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/third_party/conditions/apis/conditions/v1alpha1"
)

// WorkspaceStatusApplyConfiguration represents an declarative configuration of the WorkspaceStatus type for use
// with apply.
type WorkspaceStatusApplyConfiguration struct {
	Phase        *v1alpha1.LogicalClusterPhaseType    `json:"phase,omitempty"`
	Conditions   *conditionsv1alpha1.Conditions       `json:"conditions,omitempty"`
	Initializers []v1alpha1.LogicalClusterInitializer `json:"initializers,omitempty"`
}

// WorkspaceStatusApplyConfiguration constructs an declarative configuration of the WorkspaceStatus type for use with
// apply.
func WorkspaceStatus() *WorkspaceStatusApplyConfiguration {
	return &WorkspaceStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WorkspaceStatusApplyConfiguration) WithPhase(value v1alpha1.LogicalClusterPhaseType) *WorkspaceStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *WorkspaceStatusApplyConfiguration) WithConditions(value conditionsv1alpha1.Conditions) *WorkspaceStatusApplyConfiguration {
	b.Conditions = &value
	return b
}

// WithInitializers adds the given value to the Initializers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Initializers field.
func (b *WorkspaceStatusApplyConfiguration) WithInitializers(values ...v1alpha1.LogicalClusterInitializer) *WorkspaceStatusApplyConfiguration {
	for i := range values {
		b.Initializers = append(b.Initializers, values[i])
	}
	return b
}
