/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
	cachev1alpha1 "github.com/kcp-dev/sdk/apis/cache/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/sdk/client/applyconfiguration/cache/v1alpha1"
	typedkcpcachev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/cache/v1alpha1"
	typedcachev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/cache/v1alpha1"
)

// clusterCachedResourceEndpointSliceClusterClient implements ClusterCachedResourceEndpointSliceClusterInterface
type clusterCachedResourceEndpointSliceClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*cachev1alpha1.ClusterCachedResourceEndpointSlice, *cachev1alpha1.ClusterCachedResourceEndpointSliceList]
	Fake *kcptesting.Fake
}

func newFakeClusterCachedResourceEndpointSliceClusterClient(fake *CacheV1alpha1ClusterClient) typedkcpcachev1alpha1.ClusterCachedResourceEndpointSliceClusterInterface {
	return &clusterCachedResourceEndpointSliceClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*cachev1alpha1.ClusterCachedResourceEndpointSlice, *cachev1alpha1.ClusterCachedResourceEndpointSliceList](
			fake.Fake,
			cachev1alpha1.SchemeGroupVersion.WithResource("clustercachedresourceendpointslices"),
			cachev1alpha1.SchemeGroupVersion.WithKind("ClusterCachedResourceEndpointSlice"),
			func() *cachev1alpha1.ClusterCachedResourceEndpointSlice {
				return &cachev1alpha1.ClusterCachedResourceEndpointSlice{}
			},
			func() *cachev1alpha1.ClusterCachedResourceEndpointSliceList {
				return &cachev1alpha1.ClusterCachedResourceEndpointSliceList{}
			},
			func(dst, src *cachev1alpha1.ClusterCachedResourceEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *cachev1alpha1.ClusterCachedResourceEndpointSliceList) []*cachev1alpha1.ClusterCachedResourceEndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *cachev1alpha1.ClusterCachedResourceEndpointSliceList, items []*cachev1alpha1.ClusterCachedResourceEndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *clusterCachedResourceEndpointSliceClusterClient) Cluster(cluster logicalcluster.Path) typedcachev1alpha1.ClusterCachedResourceEndpointSliceInterface {
	return newFakeClusterCachedResourceEndpointSliceClient(c.Fake, cluster)
}

// clusterCachedResourceEndpointSliceScopedClient implements ClusterCachedResourceEndpointSliceInterface
type clusterCachedResourceEndpointSliceScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*cachev1alpha1.ClusterCachedResourceEndpointSlice, *cachev1alpha1.ClusterCachedResourceEndpointSliceList, *kcpv1alpha1.ClusterCachedResourceEndpointSliceApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeClusterCachedResourceEndpointSliceClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedcachev1alpha1.ClusterCachedResourceEndpointSliceInterface {
	return &clusterCachedResourceEndpointSliceScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*cachev1alpha1.ClusterCachedResourceEndpointSlice, *cachev1alpha1.ClusterCachedResourceEndpointSliceList, *kcpv1alpha1.ClusterCachedResourceEndpointSliceApplyConfiguration](
			fake,
			clusterPath,
			"",
			cachev1alpha1.SchemeGroupVersion.WithResource("clustercachedresourceendpointslices"),
			cachev1alpha1.SchemeGroupVersion.WithKind("ClusterCachedResourceEndpointSlice"),
			func() *cachev1alpha1.ClusterCachedResourceEndpointSlice {
				return &cachev1alpha1.ClusterCachedResourceEndpointSlice{}
			},
			func() *cachev1alpha1.ClusterCachedResourceEndpointSliceList {
				return &cachev1alpha1.ClusterCachedResourceEndpointSliceList{}
			},
			func(dst, src *cachev1alpha1.ClusterCachedResourceEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *cachev1alpha1.ClusterCachedResourceEndpointSliceList) []*cachev1alpha1.ClusterCachedResourceEndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *cachev1alpha1.ClusterCachedResourceEndpointSliceList, items []*cachev1alpha1.ClusterCachedResourceEndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
