/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	coordinationv1beta1 "k8s.io/api/coordination/v1beta1"
	v1beta1 "k8s.io/client-go/applyconfigurations/coordination/v1beta1"
	typedcoordinationv1beta1 "k8s.io/client-go/kubernetes/typed/coordination/v1beta1"

	typedkcpcoordinationv1beta1 "github.com/kcp-dev/client-go/kubernetes/typed/coordination/v1beta1"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// leaseClusterClient implements LeaseClusterInterface
type leaseClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*coordinationv1beta1.Lease, *coordinationv1beta1.LeaseList]
	Fake *kcptesting.Fake
}

func newFakeLeaseClusterClient(fake *CoordinationV1beta1ClusterClient) typedkcpcoordinationv1beta1.LeaseClusterInterface {
	return &leaseClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*coordinationv1beta1.Lease, *coordinationv1beta1.LeaseList](
			fake.Fake,
			coordinationv1beta1.SchemeGroupVersion.WithResource("leases"),
			coordinationv1beta1.SchemeGroupVersion.WithKind("Lease"),
			func() *coordinationv1beta1.Lease { return &coordinationv1beta1.Lease{} },
			func() *coordinationv1beta1.LeaseList { return &coordinationv1beta1.LeaseList{} },
			func(dst, src *coordinationv1beta1.LeaseList) { dst.ListMeta = src.ListMeta },
			func(list *coordinationv1beta1.LeaseList) []*coordinationv1beta1.Lease {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *coordinationv1beta1.LeaseList, items []*coordinationv1beta1.Lease) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *leaseClusterClient) Cluster(cluster logicalcluster.Path) typedkcpcoordinationv1beta1.LeasesNamespacer {
	return &leaseNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type leaseNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *leaseNamespacer) Namespace(namespace string) typedcoordinationv1beta1.LeaseInterface {
	return newFakeLeaseClient(n.Fake, namespace, n.ClusterPath)
}

// leaseScopedClient implements LeaseInterface
type leaseScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*coordinationv1beta1.Lease, *coordinationv1beta1.LeaseList, *v1beta1.LeaseApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeLeaseClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedcoordinationv1beta1.LeaseInterface {
	return &leaseScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*coordinationv1beta1.Lease, *coordinationv1beta1.LeaseList, *v1beta1.LeaseApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			coordinationv1beta1.SchemeGroupVersion.WithResource("leases"),
			coordinationv1beta1.SchemeGroupVersion.WithKind("Lease"),
			func() *coordinationv1beta1.Lease { return &coordinationv1beta1.Lease{} },
			func() *coordinationv1beta1.LeaseList { return &coordinationv1beta1.LeaseList{} },
			func(dst, src *coordinationv1beta1.LeaseList) { dst.ListMeta = src.ListMeta },
			func(list *coordinationv1beta1.LeaseList) []*coordinationv1beta1.Lease {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *coordinationv1beta1.LeaseList, items []*coordinationv1beta1.Lease) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
