apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcp-tls
  namespace: kcp-mcp
spec:
  secretName: mcp-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - mcp.vespucci.example.com
