/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/kcp/contrib/mounts-vw/apis/mounts/v1alpha1"
	mountsv1alpha1 "github.com/kcp-dev/kcp/contrib/mounts-vw/client/applyconfiguration/mounts/v1alpha1"
)

// FakeVClusters implements VClusterInterface
type FakeVClusters struct {
	Fake *FakeMountsV1alpha1
}

var vclustersResource = v1alpha1.SchemeGroupVersion.WithResource("vclusters")

var vclustersKind = v1alpha1.SchemeGroupVersion.WithKind("VCluster")

// Get takes name of the vCluster, and returns the corresponding vCluster object, and an error if there is any.
func (c *FakeVClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VCluster, err error) {
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(vclustersResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// List takes label and field selectors, and returns the list of VClusters that match those selectors.
func (c *FakeVClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VClusterList, err error) {
	emptyResult := &v1alpha1.VClusterList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(vclustersResource, vclustersKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VClusterList{ListMeta: obj.(*v1alpha1.VClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.VClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vClusters.
func (c *FakeVClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(vclustersResource, opts))
}

// Create takes the representation of a vCluster and creates it.  Returns the server's representation of the vCluster, and an error, if there is any.
func (c *FakeVClusters) Create(ctx context.Context, vCluster *v1alpha1.VCluster, opts v1.CreateOptions) (result *v1alpha1.VCluster, err error) {
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(vclustersResource, vCluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// Update takes the representation of a vCluster and updates it. Returns the server's representation of the vCluster, and an error, if there is any.
func (c *FakeVClusters) Update(ctx context.Context, vCluster *v1alpha1.VCluster, opts v1.UpdateOptions) (result *v1alpha1.VCluster, err error) {
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(vclustersResource, vCluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVClusters) UpdateStatus(ctx context.Context, vCluster *v1alpha1.VCluster, opts v1.UpdateOptions) (result *v1alpha1.VCluster, err error) {
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(vclustersResource, "status", vCluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// Delete takes name of the vCluster and deletes it. Returns an error if one occurs.
func (c *FakeVClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(vclustersResource, name, opts), &v1alpha1.VCluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(vclustersResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VClusterList{})
	return err
}

// Patch applies the patch and returns the patched vCluster.
func (c *FakeVClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VCluster, err error) {
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vclustersResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied vCluster.
func (c *FakeVClusters) Apply(ctx context.Context, vCluster *mountsv1alpha1.VClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VCluster, err error) {
	if vCluster == nil {
		return nil, fmt.Errorf("vCluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(vCluster)
	if err != nil {
		return nil, err
	}
	name := vCluster.Name
	if name == nil {
		return nil, fmt.Errorf("vCluster.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vclustersResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeVClusters) ApplyStatus(ctx context.Context, vCluster *mountsv1alpha1.VClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VCluster, err error) {
	if vCluster == nil {
		return nil, fmt.Errorf("vCluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(vCluster)
	if err != nil {
		return nil, err
	}
	name := vCluster.Name
	if name == nil {
		return nil, fmt.Errorf("vCluster.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.VCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vclustersResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VCluster), err
}
