//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	tenancyv1beta1 "github.com/kcp-dev/kcp/pkg/apis/tenancy/v1beta1"
	tenancyv1beta1client "github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/tenancy/v1beta1"
)

// WorkspacesClusterGetter has a method to return a WorkspaceClusterInterface.
// A group's cluster client should implement this interface.
type WorkspacesClusterGetter interface {
	Workspaces() WorkspaceClusterInterface
}

// WorkspaceClusterInterface can operate on Workspaces across all clusters,
// or scope down to one cluster and return a tenancyv1beta1client.WorkspaceInterface.
type WorkspaceClusterInterface interface {
	Cluster(logicalcluster.Path) tenancyv1beta1client.WorkspaceInterface
	List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1beta1.WorkspaceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type workspacesClusterInterface struct {
	clientCache kcpclient.Cache[*tenancyv1beta1client.TenancyV1beta1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *workspacesClusterInterface) Cluster(clusterPath logicalcluster.Path) tenancyv1beta1client.WorkspaceInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).Workspaces()
}

// List returns the entire collection of all Workspaces across all clusters.
func (c *workspacesClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1beta1.WorkspaceList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Workspaces().List(ctx, opts)
}

// Watch begins to watch all Workspaces across all clusters.
func (c *workspacesClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Workspaces().Watch(ctx, opts)
}
