
project_name: kcp
version: 2
env:
- CGO_ENABLED=0
- LDFLAGS="{{ .Env.LDFLAGS }}"

builds:
- id: "kcp"
  dir: ./cmd/kcp
  binary: bin/kcp
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
- id: "kubectl-kcp"
  main: ./cmd/kubectl-kcp
  dir: cli
  binary: bin/kubectl-kcp
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
- id: "kubectl-workspace"
  main: ./cmd/kubectl-workspace
  dir: cli
  binary: bin/kubectl-workspace
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
  hooks:
    post:
      - ln -sf kubectl-workspace bin/kubectl-workspaces
      - ln -sf kubectl-workspace bin/kubectl-ws

archives:
- id: kcp
  builds:
  - kcp
- id: kubectl-kcp-plugin
  builds:
  - kubectl-kcp
  - kubectl-workspace
  name_template: "kubectl-kcp-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - bin/kubectl-workspaces
    - bin/kubectl-ws
# krew has separate archive as it supports only one binary per plugin
- id: kubectl-kcp-plugin-krew
  builds:
  - kubectl-workspace
  name_template: "kubectl-kcp-ws-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - bin/kubectl-ws

release:
  draft: true
  mode: keep-existing

krews:
- name: ws
  ids:
  - kubectl-kcp-plugin-krew
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    KCP workspace cli plugin for kubectl. Enables you to manage your kcp workspaces.
  short_description: "KCP workspace cli plugin for kubectl."
  skip_upload: auto
