version: 2
builds:
# server builds
- id: "kcp"
  main: ./cmd/kcp
  binary: bin/kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

# plugin builds
- id: "kubectl-kcp"
  main: ./cmd/kubectl-kcp
  dir: cli
  binary: bin/kubectl-kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

- id: "kubectl-ws"
  main: ./cmd/kubectl-ws
  dir: cli
  binary: bin/kubectl-ws
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

- id: "kubectl-create-workspace"
  main: ./cmd/kubectl-create-workspace
  dir: cli
  binary: bin/kubectl-create-workspace
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

- id: apigen
  main: ./cmd/apigen
  dir: sdk
  binary: bin/apigen
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

archives:
- id: kcp
  ids:
  - kcp
- id: apigen
  ids:
  - apigen
  name_template: "apigen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-kcp-plugin
  ids:
  - kubectl-kcp
  name_template: "kubectl-kcp-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-ws-plugin
  ids:
  - kubectl-ws
  name_template: "kubectl-ws-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-create-workspace-plugin-krew
  ids:
  - kubectl-create-workspace
  name_template: "kubectl-create-workspace-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    - config/crds/crd-bundler.sh

release:
  draft: true
  mode: keep-existing
  extra_files:
    - glob: ./config/crds/crds.yaml

krews:
- name: kcp
  ids:
  - kubectl-kcp-plugin
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    kcp cli plugin for kubectl. Enables you to work with kcp.
  short_description: "kcp cli plugin for kubectl."
  skip_upload: auto
- name: ws
  ids:
  - kubectl-ws-plugin
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    kcp workspace cli plugin for kubectl. Enables you to manage your kcp workspaces.
  short_description: "kcp workspace cli plugin for kubectl."
  skip_upload: auto
- name: create-workspace
  ids:
  - kubectl-create-workspace-plugin-krew
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    kcp create workspace cli plugin for kubectl. Enables you to create kcp workspaces.
  short_description: "kcp create workspace cli plugin for kubectl."
  skip_upload: auto
