
builds:
# server builds
- id: "kcp"
  main: ./cmd/kcp
  binary: bin/kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

# plugin builds
- id: "kubectl-kcp"
  main: ./cmd/kubectl-kcp
  dir: cli
  binary: bin/kubectl-kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

- id: "kubectl-ws"
  main: ./cmd/kubectl-ws
  dir: cli
  binary: bin/kubectl-ws
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

- id: "kubectl-create-workspace"
  main: ./cmd/kubectl-create-workspace
  dir: cli
  binary: bin/kubectl-create-workspace
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0

archives:
- id: kcp
  builds:
  - kcp
- id: kubectl-kcp-plugin
  builds:
  - kubectl-kcp
  name_template: "kubectl-kcp-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-ws-plugin
  builds:
  - kubectl-ws
  name_template: "kubectl-ws-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-create-workspace-plugin-krew
  builds:
  - kubectl-create-workspace
  name_template: "kubectl-create-workspace-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  draft: true
  mode: keep-existing

krews:
- name: kcp
  ids:
  - kubectl-kcp-plugin
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    KCP cli plugin for kubectl. Enables you to work with KCP.
  short_description: "KCP cli plugin for kubectl."
  skip_upload: auto
- name: ws
  ids:
  - kubectl-ws-plugin
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    KCP workspace cli plugin for kubectl. Enables you to manage your KCP workspaces.
  short_description: "KCP workspace cli plugin for kubectl."
  skip_upload: auto
- name: create-workspace
  ids:
  - kubectl-create-workspace-plugin-krew
  repository:
    owner: kcp-dev
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kcp.io/"
  description: |
    KCP create workspace cli plugin for kubectl. Enables you to create KCP workspaces.
  short_description: "KCP create workspace cli plugin for kubectl."
  skip_upload: auto
