apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data:
    server: https://kcp.faros.sh:443
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVTV1VHRGxiZGpKbTRqQXZIUTBzRV9iRk55TFFiSnpfS2o2c1BmN2lGaHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jbHVzdGVyTmFtZSI6ImZ5dHZhOTE3MHc0aGEyaHoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L25hbWVzcGFjZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoia2NwLXByb3h5LXRpbHQtanU5cmFwa2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoia2NwLXByb3h5LXRpbHQtanU5cmFwa2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3ZjRjYjgyMC1kODI5LTQ5NTAtYWFiOC1mZjhlNmI4MzgxYTkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDprY3AtcHJveHktdGlsdC1qdTlyYXBrayJ9.MRikWJJON3pXAW0WEKdioKvQS8ONhTUs6kpTuCVHTOocAwDqFo5nKE-Nbai6qF5DvxAu3wDPIZnprEc7EmHxCSdFVjizWeO8b4Kauo30Nj0Dm7yVATCWNhr6dmb1VnVfyeDfmFrCox8OK41Cw8fuS80lhHrAJDW980CvHTfJwwSY_-jHHx-fPOH7nuo0Y8skhgOkPFE_-d3g0KftM4fRHd19kDF7EVSjk_YTtOvNFF89cqH7AtKPUMLSaoePgxliFCyx8Zsk7UyZKHHAYuh0v687sOdh-S8n16Q8T2_eO7Pb0exNhBd8YKo3w4lbHR2r4dZg0SRgo-0GlAxrQkLC1w
