---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: kcp-comer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp-ca
  namespace: kcp-comer
spec:
  secretName: kcp-ca-tls
  isCA: true
  commonName: kcp-ca
  issuerRef:
    name: selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kcp-ca
  namespace: kcp-comer
spec:
  ca:
    secretName: kcp-ca-tls