/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1

import (
	"github.com/kcp-dev/logicalcluster/v3"

	kcplisters "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/listers"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	existinginterfacesv1 "acme.corp/pkg/apis/existinginterfaces/v1"
	listersexistinginterfacesv1 "acme.corp/pkg/generated/listers/existinginterfaces/v1"
)

// TestTypeClusterLister helps list TestTypes across all workspaces,
// or scope down to a TestTypeLister for one workspace.
// All objects returned here must be treated as read-only.
type TestTypeClusterLister interface {
	// List lists all TestTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*existinginterfacesv1.TestType, err error)
	// Cluster returns a lister that can list and get TestTypes in one workspace.
	Cluster(clusterName logicalcluster.Name) listersexistinginterfacesv1.TestTypeLister
	TestTypeClusterListerExpansion
}

// testTypeClusterLister implements the TestTypeClusterLister interface.
type testTypeClusterLister struct {
	kcplisters.ResourceClusterIndexer[*existinginterfacesv1.TestType]
}

var _ TestTypeClusterLister = new(testTypeClusterLister)

// NewTestTypeClusterLister returns a new TestTypeClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewTestTypeClusterLister(indexer cache.Indexer) TestTypeClusterLister {
	return &testTypeClusterLister{
		kcplisters.NewCluster[*existinginterfacesv1.TestType](indexer, existinginterfacesv1.Resource("testtype")),
	}
}

// Cluster scopes the lister to one workspace, allowing users to list and get TestTypes.
func (l *testTypeClusterLister) Cluster(clusterName logicalcluster.Name) listersexistinginterfacesv1.TestTypeLister {
	return &testTypeLister{
		l.ResourceClusterIndexer.WithCluster(clusterName),
	}
}

// testTypeLister can list all TestTypes inside a workspace
// or scope down to a listersexistinginterfacesv1.TestTypeNamespaceLister for one namespace.
type testTypeLister struct {
	kcplisters.ResourceIndexer[*existinginterfacesv1.TestType]
}

var _ listersexistinginterfacesv1.TestTypeLister = new(testTypeLister)

// TestTypes returns an object that can list and get TestTypes in one namespace.
func (l *testTypeLister) TestTypes(namespace string) listersexistinginterfacesv1.TestTypeNamespaceLister {
	return &testTypeNamespaceLister{
		l.ResourceIndexer.WithNamespace(namespace),
	}
}

// testTypeNamespaceLister implements the listersexistinginterfacesv1.TestTypeNamespaceLister
// interface.
type testTypeNamespaceLister struct {
	kcplisters.ResourceIndexer[*existinginterfacesv1.TestType]
}

var _ listersexistinginterfacesv1.TestTypeNamespaceLister = new(testTypeNamespaceLister)

// NewTestTypeLister returns a new TestTypeLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewTestTypeLister(indexer cache.Indexer) listersexistinginterfacesv1.TestTypeLister {
	return &testTypeLister{
		kcplisters.New[*existinginterfacesv1.TestType](indexer, existinginterfacesv1.Resource("testtype")),
	}
}

// testTypeScopedLister can list all TestTypes inside a workspace
// or scope down to a listersexistinginterfacesv1.TestTypeNamespaceLister for one namespace.
type testTypeScopedLister struct {
	kcplisters.ResourceIndexer[*existinginterfacesv1.TestType]
}

// TestTypes returns an object that can list and get TestTypes in one namespace.
func (l *testTypeScopedLister) TestTypes(namespace string) listersexistinginterfacesv1.TestTypeLister {
	return &testTypeLister{
		l.ResourceIndexer.WithNamespace(namespace),
	}
}
