/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	resourcev1beta2 "k8s.io/api/resource/v1beta2"
	v1beta2 "k8s.io/client-go/applyconfigurations/resource/v1beta2"
	typedresourcev1beta2 "k8s.io/client-go/kubernetes/typed/resource/v1beta2"

	typedkcpresourcev1beta2 "github.com/kcp-dev/client-go/kubernetes/typed/resource/v1beta2"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
)

// deviceTaintRuleClusterClient implements DeviceTaintRuleClusterInterface
type deviceTaintRuleClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*resourcev1beta2.DeviceTaintRule, *resourcev1beta2.DeviceTaintRuleList]
	Fake *kcptesting.Fake
}

func newFakeDeviceTaintRuleClusterClient(fake *ResourceV1beta2ClusterClient) typedkcpresourcev1beta2.DeviceTaintRuleClusterInterface {
	return &deviceTaintRuleClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*resourcev1beta2.DeviceTaintRule, *resourcev1beta2.DeviceTaintRuleList](
			fake.Fake,
			resourcev1beta2.SchemeGroupVersion.WithResource("devicetaintrules"),
			resourcev1beta2.SchemeGroupVersion.WithKind("DeviceTaintRule"),
			func() *resourcev1beta2.DeviceTaintRule { return &resourcev1beta2.DeviceTaintRule{} },
			func() *resourcev1beta2.DeviceTaintRuleList { return &resourcev1beta2.DeviceTaintRuleList{} },
			func(dst, src *resourcev1beta2.DeviceTaintRuleList) { dst.ListMeta = src.ListMeta },
			func(list *resourcev1beta2.DeviceTaintRuleList) []*resourcev1beta2.DeviceTaintRule {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *resourcev1beta2.DeviceTaintRuleList, items []*resourcev1beta2.DeviceTaintRule) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *deviceTaintRuleClusterClient) Cluster(cluster logicalcluster.Path) typedresourcev1beta2.DeviceTaintRuleInterface {
	return newFakeDeviceTaintRuleClient(c.Fake, cluster)
}

// deviceTaintRuleScopedClient implements DeviceTaintRuleInterface
type deviceTaintRuleScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*resourcev1beta2.DeviceTaintRule, *resourcev1beta2.DeviceTaintRuleList, *v1beta2.DeviceTaintRuleApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeDeviceTaintRuleClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedresourcev1beta2.DeviceTaintRuleInterface {
	return &deviceTaintRuleScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*resourcev1beta2.DeviceTaintRule, *resourcev1beta2.DeviceTaintRuleList, *v1beta2.DeviceTaintRuleApplyConfiguration](
			fake,
			clusterPath,
			"",
			resourcev1beta2.SchemeGroupVersion.WithResource("devicetaintrules"),
			resourcev1beta2.SchemeGroupVersion.WithKind("DeviceTaintRule"),
			func() *resourcev1beta2.DeviceTaintRule { return &resourcev1beta2.DeviceTaintRule{} },
			func() *resourcev1beta2.DeviceTaintRuleList { return &resourcev1beta2.DeviceTaintRuleList{} },
			func(dst, src *resourcev1beta2.DeviceTaintRuleList) { dst.ListMeta = src.ListMeta },
			func(list *resourcev1beta2.DeviceTaintRuleList) []*resourcev1beta2.DeviceTaintRule {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *resourcev1beta2.DeviceTaintRuleList, items []*resourcev1beta2.DeviceTaintRule) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
