apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: migration.kcp.io
spec:
  resources:
  - group: migration.kcp.io
    name: logicalclusterdumps
    schema: v260604-70219e163.logicalclusterdumps.migration.kcp.io
    storage:
      crd: {}
  - group: migration.kcp.io
    name: logicalclustermigrations
    schema: v260624-65ebd3edd.logicalclustermigrations.migration.kcp.io
    storage:
      crd: {}
status: {}
