apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: migration.kcp.io
spec:
  resources:
  - group: migration.kcp.io
    name: logicalclusterdumps
    schema: v260702-7381341f5.logicalclusterdumps.migration.kcp.io
    storage:
      crd: {}
  - group: migration.kcp.io
    name: logicalclustermigrations
    schema: v260702-7381341f5.logicalclustermigrations.migration.kcp.io
    storage:
      crd: {}
status: {}
