apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: cache.kcp.io
spec:
  resources:
  - group: cache.kcp.io
    name: publishedresources
    schema: v250418-140e81193.publishedresources.cache.kcp.io
    storage:
      crd: {}
status: {}
