apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: shards.tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v220802-5aa7c1c9.clusterworkspaceshards.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
