apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: cache.kcp.io
spec:
  resources:
  - group: cache.kcp.io
    name: clustercachedresourceendpointslices
    schema: v260407-65ee8229a.clustercachedresourceendpointslices.cache.kcp.io
    storage:
      crd: {}
  - group: cache.kcp.io
    name: clustercachedresources
    schema: v250920-de0c8484d.clustercachedresources.cache.kcp.io
    storage:
      crd: {}
status: {}
