apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: core.kcp.io
spec:
  resources:
  - group: core.kcp.io
    name: caches
    schema: v260826-9a0fa5322.caches.core.kcp.io
    storage:
      crd: {}
status: {}
