apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v250604-36e6abf17.cachedresourceendpointslices.cache.kcp.io
spec:
  group: cache.kcp.io
  names:
    categories:
    - kcp
    kind: CachedResourceEndpointSlice
    listKind: CachedResourceEndpointSliceList
    plural: cachedresourceendpointslices
    singular: cachedresourceendpointslice
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.cachedResource.name
      name: CachedResource
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      description: CachedResourceEndpointSlice is a sink for the endpoints of CachedResource
        virtual workspaces.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: |-
            spec holds the desired state:
            - the targeted CachedResource
          properties:
            cachedResource:
              description: CachedResource points to the real CachedResource the slice
                is created for.
              properties:
                name:
                  description: name is the name of the CachedResource the reference
                    points to.
                  type: string
              required:
              - name
              type: object
              x-kubernetes-validations:
              - message: CachedResource reference must not be changed
                rule: self == oldSelf
          required:
          - cachedResource
          type: object
        status:
          description: |-
            status communicates the observed state:
            the filtered list of endpoints for the Replication service.
          properties:
            endpoints:
              description: endpoints contains all the URLs of the Replication service.
              items:
                description: CachedResourceEndpoint contains the endpoint information
                  of a Replication service for a specific shard.
                properties:
                  url:
                    description: url is an CachedResource virtual workspace URL.
                    minLength: 1
                    type: string
                required:
                - url
                type: object
              type: array
              x-kubernetes-list-map-keys:
              - url
              x-kubernetes-list-type: map
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
