/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v2 "github.com/kcp-dev/logicalcluster/v2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tenancy/v1alpha1"
	scheme "github.com/kcp-dev/kcp/pkg/client/clientset/versioned/scheme"
)

// ClusterWorkspaceTypesGetter has a method to return a ClusterWorkspaceTypeInterface.
// A group's client should implement this interface.
type ClusterWorkspaceTypesGetter interface {
	ClusterWorkspaceTypes() ClusterWorkspaceTypeInterface
}

// ClusterWorkspaceTypeInterface has methods to work with ClusterWorkspaceType resources.
type ClusterWorkspaceTypeInterface interface {
	Create(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.CreateOptions) (*v1alpha1.ClusterWorkspaceType, error)
	Update(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.UpdateOptions) (*v1alpha1.ClusterWorkspaceType, error)
	UpdateStatus(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.UpdateOptions) (*v1alpha1.ClusterWorkspaceType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterWorkspaceType, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterWorkspaceTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterWorkspaceType, err error)
	ClusterWorkspaceTypeExpansion
}

// clusterWorkspaceTypes implements ClusterWorkspaceTypeInterface
type clusterWorkspaceTypes struct {
	client  rest.Interface
	cluster v2.Name
}

// newClusterWorkspaceTypes returns a ClusterWorkspaceTypes
func newClusterWorkspaceTypes(c *TenancyV1alpha1Client) *clusterWorkspaceTypes {
	return &clusterWorkspaceTypes{
		client:  c.RESTClient(),
		cluster: c.cluster,
	}
}

// Get takes name of the clusterWorkspaceType, and returns the corresponding clusterWorkspaceType object, and an error if there is any.
func (c *clusterWorkspaceTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterWorkspaceType, err error) {
	result = &v1alpha1.ClusterWorkspaceType{}
	err = c.client.Get().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterWorkspaceTypes that match those selectors.
func (c *clusterWorkspaceTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterWorkspaceTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterWorkspaceTypeList{}
	err = c.client.Get().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterWorkspaceTypes.
func (c *clusterWorkspaceTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterWorkspaceType and creates it.  Returns the server's representation of the clusterWorkspaceType, and an error, if there is any.
func (c *clusterWorkspaceTypes) Create(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.CreateOptions) (result *v1alpha1.ClusterWorkspaceType, err error) {
	result = &v1alpha1.ClusterWorkspaceType{}
	err = c.client.Post().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterWorkspaceType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterWorkspaceType and updates it. Returns the server's representation of the clusterWorkspaceType, and an error, if there is any.
func (c *clusterWorkspaceTypes) Update(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.UpdateOptions) (result *v1alpha1.ClusterWorkspaceType, err error) {
	result = &v1alpha1.ClusterWorkspaceType{}
	err = c.client.Put().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		Name(clusterWorkspaceType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterWorkspaceType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterWorkspaceTypes) UpdateStatus(ctx context.Context, clusterWorkspaceType *v1alpha1.ClusterWorkspaceType, opts v1.UpdateOptions) (result *v1alpha1.ClusterWorkspaceType, err error) {
	result = &v1alpha1.ClusterWorkspaceType{}
	err = c.client.Put().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		Name(clusterWorkspaceType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterWorkspaceType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterWorkspaceType and deletes it. Returns an error if one occurs.
func (c *clusterWorkspaceTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterWorkspaceTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterWorkspaceType.
func (c *clusterWorkspaceTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterWorkspaceType, err error) {
	result = &v1alpha1.ClusterWorkspaceType{}
	err = c.client.Patch(pt).
		Cluster(c.cluster).
		Resource("clusterworkspacetypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
