/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	storagev1beta1 "k8s.io/api/storage/v1beta1"
	v1beta1 "k8s.io/client-go/applyconfigurations/storage/v1beta1"
	typedstoragev1beta1 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"

	typedkcpstoragev1beta1 "github.com/kcp-dev/client-go/kubernetes/typed/storage/v1beta1"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// cSIDriverClusterClient implements CSIDriverClusterInterface
type cSIDriverClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*storagev1beta1.CSIDriver, *storagev1beta1.CSIDriverList]
	Fake *kcptesting.Fake
}

func newFakeCSIDriverClusterClient(fake *StorageV1beta1ClusterClient) typedkcpstoragev1beta1.CSIDriverClusterInterface {
	return &cSIDriverClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*storagev1beta1.CSIDriver, *storagev1beta1.CSIDriverList](
			fake.Fake,
			storagev1beta1.SchemeGroupVersion.WithResource("csidrivers"),
			storagev1beta1.SchemeGroupVersion.WithKind("CSIDriver"),
			func() *storagev1beta1.CSIDriver { return &storagev1beta1.CSIDriver{} },
			func() *storagev1beta1.CSIDriverList { return &storagev1beta1.CSIDriverList{} },
			func(dst, src *storagev1beta1.CSIDriverList) { dst.ListMeta = src.ListMeta },
			func(list *storagev1beta1.CSIDriverList) []*storagev1beta1.CSIDriver {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *storagev1beta1.CSIDriverList, items []*storagev1beta1.CSIDriver) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *cSIDriverClusterClient) Cluster(cluster logicalcluster.Path) typedstoragev1beta1.CSIDriverInterface {
	return newFakeCSIDriverClient(c.Fake, cluster)
}

// cSIDriverScopedClient implements CSIDriverInterface
type cSIDriverScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*storagev1beta1.CSIDriver, *storagev1beta1.CSIDriverList, *v1beta1.CSIDriverApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeCSIDriverClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedstoragev1beta1.CSIDriverInterface {
	return &cSIDriverScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*storagev1beta1.CSIDriver, *storagev1beta1.CSIDriverList, *v1beta1.CSIDriverApplyConfiguration](
			fake,
			clusterPath,
			"",
			storagev1beta1.SchemeGroupVersion.WithResource("csidrivers"),
			storagev1beta1.SchemeGroupVersion.WithKind("CSIDriver"),
			func() *storagev1beta1.CSIDriver { return &storagev1beta1.CSIDriver{} },
			func() *storagev1beta1.CSIDriverList { return &storagev1beta1.CSIDriverList{} },
			func(dst, src *storagev1beta1.CSIDriverList) { dst.ListMeta = src.ListMeta },
			func(list *storagev1beta1.CSIDriverList) []*storagev1beta1.CSIDriver {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *storagev1beta1.CSIDriverList, items []*storagev1beta1.CSIDriver) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
