/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	v1alpha1 "github.com/kcp-dev/kcp/contrib/mounts-vw/apis/proxy/v1alpha1"
	proxyv1alpha1 "github.com/kcp-dev/kcp/contrib/mounts-vw/client/applyconfiguration/proxy/v1alpha1"
	scheme "github.com/kcp-dev/kcp/contrib/mounts-vw/client/clientset/versioned/scheme"
)

// TargetKubeClustersGetter has a method to return a TargetKubeClusterInterface.
// A group's client should implement this interface.
type TargetKubeClustersGetter interface {
	TargetKubeClusters() TargetKubeClusterInterface
}

// TargetKubeClusterInterface has methods to work with TargetKubeCluster resources.
type TargetKubeClusterInterface interface {
	Create(ctx context.Context, targetKubeCluster *v1alpha1.TargetKubeCluster, opts v1.CreateOptions) (*v1alpha1.TargetKubeCluster, error)
	Update(ctx context.Context, targetKubeCluster *v1alpha1.TargetKubeCluster, opts v1.UpdateOptions) (*v1alpha1.TargetKubeCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, targetKubeCluster *v1alpha1.TargetKubeCluster, opts v1.UpdateOptions) (*v1alpha1.TargetKubeCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TargetKubeCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TargetKubeClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TargetKubeCluster, err error)
	Apply(ctx context.Context, targetKubeCluster *proxyv1alpha1.TargetKubeClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TargetKubeCluster, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, targetKubeCluster *proxyv1alpha1.TargetKubeClusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TargetKubeCluster, err error)
	TargetKubeClusterExpansion
}

// targetKubeClusters implements TargetKubeClusterInterface
type targetKubeClusters struct {
	*gentype.ClientWithListAndApply[*v1alpha1.TargetKubeCluster, *v1alpha1.TargetKubeClusterList, *proxyv1alpha1.TargetKubeClusterApplyConfiguration]
}

// newTargetKubeClusters returns a TargetKubeClusters
func newTargetKubeClusters(c *ProxyV1alpha1Client) *targetKubeClusters {
	return &targetKubeClusters{
		gentype.NewClientWithListAndApply[*v1alpha1.TargetKubeCluster, *v1alpha1.TargetKubeClusterList, *proxyv1alpha1.TargetKubeClusterApplyConfiguration](
			"targetkubeclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.TargetKubeCluster { return &v1alpha1.TargetKubeCluster{} },
			func() *v1alpha1.TargetKubeClusterList { return &v1alpha1.TargetKubeClusterList{} }),
	}
}
