---
apiVersion: mounts.contrib.kcp.io/v1alpha1
kind: VCluster
metadata:
  name: virtual-cluster
  annotations:
    experimental.tenancy.kcp.io/is-mount: "true"
spec:
  mode: Delegated
  secretString: -azOM-pgm7XRwMtg
