ARG SHELL=""

FROM alpine

RUN apk --no-cache add ca-certificates \
  && update-ca-certificates ca-certificates-bundle

RUN apk --no-cache add curl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin

WORKDIR /
COPY bin/kcp-front-proxy .

ENTRYPOINT ["./kcp-front-proxy"]
