externalHostname: "kcp.faros.sh"
kcp:
  volumeClassName: "standard"
  externalLogicalClusterAdminFlag: false
  # Fake images to trick Tilt to think they are different
  image: "ghcr.io/kcp-dev/kcp-server"
  tokenAuth:
    enabled: true
    fileName: auth-token.csv
    config: |
        admin-token,admin,5555-5555-5555-5555,"system:kcp:admin"
        system-token,system,6666-6666-6666-6666,"system:admin"
  v: 3
kcpFrontProxy:
  # Fake images to trick Tilt to think they are different
  image: "ghcr.io/kcp-dev/kcp-frontend-proxy"
  tag: f1332a0e
  openshiftRoute:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  certificate:
    issuerSpec:
      selfSigned: {}
layered:
  proxy:
    enabled: true
    token: admin-token
