server:
  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
extraScrapeConfigs: |
   - job_name: 'kcp'
     metrics_path: /metrics
     tls_config:
       insecure_skip_verify: true
     scheme: https
     static_configs:
       - targets:
         - kcp.kcp.svc.cluster.local:6443
     bearer_token: eyJhbGciOiJSUzI1NiIsImtpZCI6InpHNXFUcnJ3a1VQUXFmQ3BHMXcxZ3V3eldNblRiM01MMDlzbm9aUkxpRjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jbHVzdGVyTmFtZSI6InJvb3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L25hbWVzcGFjZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoia3ViZS1tZXRyaWNzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imt1YmUtbWV0cmljcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE5NmQyODk0LWY2Y2YtNGU5NC1hMDk5LWU4OWU4MGFkM2Q4OSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Omt1YmUtbWV0cmljcyJ9.ZRWXpXJngrBsbr5uoW6Zv-6pEfYnnJziTvXvLPCjI_2QKvrOyU83nMkoBmKQmMcxqk-XyiHQz0IPXdN6UlTdkqTxl6_ZEc7wEzBDaNOdnct-ZfcLDl3dRjFSRpN6th5HafuZHdDGyIXT5S7BI1_j_1rwspAnIPrTnL2Ovo0Ux-xosBysDfT9HY3dpcx3Mkl7i8v09wLo0Ksjdx7AsAG_KL7rzWZ_tQnBv4iqgQc8yevxEuVGru-oMbZ_A3gSuI6MFPGSQZkMLcLdLuRjUKC-MliG9DvAf9CPyd5e19VUpWmEaDijhzBT-ePAGoK-QR3uGYASqLTyRc_6efGqmnrd7g
