/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	tenancyv1alpha1 "github.com/kcp-dev/sdk/apis/tenancy/v1alpha1"
)

// WorkspaceTypeSpecApplyConfiguration represents a declarative configuration of the WorkspaceTypeSpec type for use
// with apply.
type WorkspaceTypeSpecApplyConfiguration struct {
	// initializer determines if this WorkspaceType has an associated initializing
	// controller. These controllers are used to add functionality to a Workspace;
	// all controllers must finish their work before the Workspace becomes ready
	// for use.
	//
	// One initializing controller is supported per WorkspaceType; the identifier
	// for this initializer will be a colon-delimited string using the workspace in which
	// the WorkspaceType is defined, and the type's name. For example, if a
	// WorkspaceType `example` is created in the `root:org` workspace, the implicit
	// initializer name is `root:org:example`.
	Initializer *bool `json:"initializer,omitempty"`
	// Terminator determines if this WorkspaceType has an associated terminating
	// controller. These controllers are used to add functionality to a Workspace;
	// all controllers must finish their work before the Workspace is being deleted.
	//
	// One terminating controller is supported per WorkspaceType; the identifier
	// for this terminator will be a colon-delimited string using the workspace in which
	// the WorkspaceType is defined, and the type's name. For example, if a
	// WorkspaceType `example` is created in the `root:org` workspace, the implicit
	// terminator name is `root:org:example`.
	Terminator *bool `json:"terminator,omitempty"`
	// extend is a list of other WorkspaceTypes whose initializers and limitAllowedChildren
	// and limitAllowedParents this WorkspaceType is inheriting. By (transitively) extending
	// another WorkspaceType, this WorkspaceType will be considered as that
	// other type in evaluation of limitAllowedChildren and limitAllowedParents constraints.
	//
	// A dependency cycle stop this WorkspaceType from being admitted as the type
	// of a Workspace.
	//
	// A non-existing dependency stop this WorkspaceType from being admitted as the type
	// of a Workspace.
	Extend *WorkspaceTypeExtensionApplyConfiguration `json:"extend,omitempty"`
	// additionalWorkspaceLabels are a set of labels that will be added to a
	// Workspace on creation.
	AdditionalWorkspaceLabels map[string]string `json:"additionalWorkspaceLabels,omitempty"`
	// defaultChildWorkspaceType is the WorkspaceType that will be used
	// by default if another, nested Workspace is created in a workspace
	// of this type. When this field is unset, the user must specify a type when
	// creating nested workspaces. Extending another WorkspaceType does
	// not inherit its defaultChildWorkspaceType.
	DefaultChildWorkspaceType *WorkspaceTypeReferenceApplyConfiguration `json:"defaultChildWorkspaceType,omitempty"`
	// limitAllowedChildren specifies constraints for sub-workspaces created in workspaces
	// of this type. These are in addition to child constraints of types this one extends.
	LimitAllowedChildren *WorkspaceTypeSelectorApplyConfiguration `json:"limitAllowedChildren,omitempty"`
	// limitAllowedParents specifies constraints for the parent workspace that workspaces
	// of this type are created in. These are in addition to parent constraints of types this one
	// extends.
	LimitAllowedParents *WorkspaceTypeSelectorApplyConfiguration `json:"limitAllowedParents,omitempty"`
	// defaultAPIBindings are the APIs to bind during initialization of workspaces created from this type.
	// The APIBinding names will be generated dynamically.
	DefaultAPIBindings []APIExportReferenceApplyConfiguration `json:"defaultAPIBindings,omitempty"`
	// Configure the lifecycle behaviour of defaultAPIBindings.
	DefaultAPIBindingLifecycle *tenancyv1alpha1.APIBindingLifecycleMode `json:"defaultAPIBindingLifecycle,omitempty"`
	// authenticationConfigurations are additional authentication options that should apply to any
	// workspace using this workspace type.
	AuthenticationConfigurations []AuthenticationConfigurationReferenceApplyConfiguration `json:"authenticationConfigurations,omitempty"`
}

// WorkspaceTypeSpecApplyConfiguration constructs a declarative configuration of the WorkspaceTypeSpec type for use with
// apply.
func WorkspaceTypeSpec() *WorkspaceTypeSpecApplyConfiguration {
	return &WorkspaceTypeSpecApplyConfiguration{}
}

// WithInitializer sets the Initializer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Initializer field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithInitializer(value bool) *WorkspaceTypeSpecApplyConfiguration {
	b.Initializer = &value
	return b
}

// WithTerminator sets the Terminator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Terminator field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithTerminator(value bool) *WorkspaceTypeSpecApplyConfiguration {
	b.Terminator = &value
	return b
}

// WithExtend sets the Extend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Extend field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithExtend(value *WorkspaceTypeExtensionApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	b.Extend = value
	return b
}

// WithAdditionalWorkspaceLabels puts the entries into the AdditionalWorkspaceLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalWorkspaceLabels field,
// overwriting an existing map entries in AdditionalWorkspaceLabels field with the same key.
func (b *WorkspaceTypeSpecApplyConfiguration) WithAdditionalWorkspaceLabels(entries map[string]string) *WorkspaceTypeSpecApplyConfiguration {
	if b.AdditionalWorkspaceLabels == nil && len(entries) > 0 {
		b.AdditionalWorkspaceLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AdditionalWorkspaceLabels[k] = v
	}
	return b
}

// WithDefaultChildWorkspaceType sets the DefaultChildWorkspaceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultChildWorkspaceType field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithDefaultChildWorkspaceType(value *WorkspaceTypeReferenceApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	b.DefaultChildWorkspaceType = value
	return b
}

// WithLimitAllowedChildren sets the LimitAllowedChildren field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LimitAllowedChildren field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithLimitAllowedChildren(value *WorkspaceTypeSelectorApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	b.LimitAllowedChildren = value
	return b
}

// WithLimitAllowedParents sets the LimitAllowedParents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LimitAllowedParents field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithLimitAllowedParents(value *WorkspaceTypeSelectorApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	b.LimitAllowedParents = value
	return b
}

// WithDefaultAPIBindings adds the given value to the DefaultAPIBindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DefaultAPIBindings field.
func (b *WorkspaceTypeSpecApplyConfiguration) WithDefaultAPIBindings(values ...*APIExportReferenceApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefaultAPIBindings")
		}
		b.DefaultAPIBindings = append(b.DefaultAPIBindings, *values[i])
	}
	return b
}

// WithDefaultAPIBindingLifecycle sets the DefaultAPIBindingLifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultAPIBindingLifecycle field is set to the value of the last call.
func (b *WorkspaceTypeSpecApplyConfiguration) WithDefaultAPIBindingLifecycle(value tenancyv1alpha1.APIBindingLifecycleMode) *WorkspaceTypeSpecApplyConfiguration {
	b.DefaultAPIBindingLifecycle = &value
	return b
}

// WithAuthenticationConfigurations adds the given value to the AuthenticationConfigurations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthenticationConfigurations field.
func (b *WorkspaceTypeSpecApplyConfiguration) WithAuthenticationConfigurations(values ...*AuthenticationConfigurationReferenceApplyConfiguration) *WorkspaceTypeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAuthenticationConfigurations")
		}
		b.AuthenticationConfigurations = append(b.AuthenticationConfigurations, *values[i])
	}
	return b
}
