/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	discoveryv1beta1 "k8s.io/api/discovery/v1beta1"
	v1beta1 "k8s.io/client-go/applyconfigurations/discovery/v1beta1"
	typeddiscoveryv1beta1 "k8s.io/client-go/kubernetes/typed/discovery/v1beta1"

	typedkcpdiscoveryv1beta1 "github.com/kcp-dev/client-go/kubernetes/typed/discovery/v1beta1"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// endpointSliceClusterClient implements EndpointSliceClusterInterface
type endpointSliceClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*discoveryv1beta1.EndpointSlice, *discoveryv1beta1.EndpointSliceList]
	Fake *kcptesting.Fake
}

func newFakeEndpointSliceClusterClient(fake *DiscoveryV1beta1ClusterClient) typedkcpdiscoveryv1beta1.EndpointSliceClusterInterface {
	return &endpointSliceClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*discoveryv1beta1.EndpointSlice, *discoveryv1beta1.EndpointSliceList](
			fake.Fake,
			discoveryv1beta1.SchemeGroupVersion.WithResource("endpointslices"),
			discoveryv1beta1.SchemeGroupVersion.WithKind("EndpointSlice"),
			func() *discoveryv1beta1.EndpointSlice { return &discoveryv1beta1.EndpointSlice{} },
			func() *discoveryv1beta1.EndpointSliceList { return &discoveryv1beta1.EndpointSliceList{} },
			func(dst, src *discoveryv1beta1.EndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *discoveryv1beta1.EndpointSliceList) []*discoveryv1beta1.EndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *discoveryv1beta1.EndpointSliceList, items []*discoveryv1beta1.EndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *endpointSliceClusterClient) Cluster(cluster logicalcluster.Path) typedkcpdiscoveryv1beta1.EndpointSlicesNamespacer {
	return &endpointSliceNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type endpointSliceNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *endpointSliceNamespacer) Namespace(namespace string) typeddiscoveryv1beta1.EndpointSliceInterface {
	return newFakeEndpointSliceClient(n.Fake, namespace, n.ClusterPath)
}

// endpointSliceScopedClient implements EndpointSliceInterface
type endpointSliceScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*discoveryv1beta1.EndpointSlice, *discoveryv1beta1.EndpointSliceList, *v1beta1.EndpointSliceApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeEndpointSliceClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typeddiscoveryv1beta1.EndpointSliceInterface {
	return &endpointSliceScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*discoveryv1beta1.EndpointSlice, *discoveryv1beta1.EndpointSliceList, *v1beta1.EndpointSliceApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			discoveryv1beta1.SchemeGroupVersion.WithResource("endpointslices"),
			discoveryv1beta1.SchemeGroupVersion.WithKind("EndpointSlice"),
			func() *discoveryv1beta1.EndpointSlice { return &discoveryv1beta1.EndpointSlice{} },
			func() *discoveryv1beta1.EndpointSliceList { return &discoveryv1beta1.EndpointSliceList{} },
			func(dst, src *discoveryv1beta1.EndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *discoveryv1beta1.EndpointSliceList) []*discoveryv1beta1.EndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *discoveryv1beta1.EndpointSliceList, items []*discoveryv1beta1.EndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
