name: Community Meeting Agenda
description: Create a new weekly meeting agenda
title: "Community Meeting [DATE]"
labels:
  - community-meeting
body:
  - type: textarea
    attributes:
      label: Overview
      value: |
        At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

        Video call link: https://meet.google.com/mpd-cypd-sdp
        Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
        More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
        Or join via SIP: sip:5005991305702@gmeet.redhat.com

        Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

        Add topics you'd like to discuss below!
    validations:
      required: true
