apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mangodbs.mangodb.com
  labels:
    kube-bind.io/exported: "true"
spec:
  group: mangodb.com
  names:
    kind: MangoDB
    listKind: MangoDBList
    plural: mangodbs
    singular: mangodb
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tier:
                type: string
                enum:
                - Dedicated
                - Shared
                default: Shared
              region:
                type: string
                default: us-east-1
                minLength: 1
              backup:
                type: boolean
                default: false
              tokenSecret:
                type: string
                minLength: 1
            required:
            - tokenSecret
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Running
                - Succeeded
                - Failed
                - Unknown
        required:
        - spec
