/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResourceSourceApplyConfiguration represents a declarative configuration of the ResourceSource type for use
// with apply.
type ResourceSourceApplyConfiguration struct {
	Cluster  *string                              `json:"cluster,omitempty"`
	Resource *ResourceReferenceApplyConfiguration `json:"resource,omitempty"`
}

// ResourceSourceApplyConfiguration constructs a declarative configuration of the ResourceSource type for use with
// apply.
func ResourceSource() *ResourceSourceApplyConfiguration {
	return &ResourceSourceApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *ResourceSourceApplyConfiguration) WithCluster(value string) *ResourceSourceApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ResourceSourceApplyConfiguration) WithResource(value *ResourceReferenceApplyConfiguration) *ResourceSourceApplyConfiguration {
	b.Resource = value
	return b
}
