/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/kcp-dev/logicalcluster/v3"

	storagev1beta1 "k8s.io/api/storage/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	listersstoragev1beta1 "k8s.io/client-go/listers/storage/v1beta1"
	"k8s.io/client-go/tools/cache"

	kcplisters "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/listers"
)

// CSIDriverClusterLister helps list CSIDrivers across all workspaces,
// or scope down to a CSIDriverLister for one workspace.
// All objects returned here must be treated as read-only.
type CSIDriverClusterLister interface {
	// List lists all CSIDrivers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1beta1.CSIDriver, err error)
	// Cluster returns a lister that can list and get CSIDrivers in one workspace.
	Cluster(clusterName logicalcluster.Name) listersstoragev1beta1.CSIDriverLister
	CSIDriverClusterListerExpansion
}

// cSIDriverClusterLister implements the CSIDriverClusterLister interface.
type cSIDriverClusterLister struct {
	kcplisters.ResourceClusterIndexer[*storagev1beta1.CSIDriver]
}

var _ CSIDriverClusterLister = new(cSIDriverClusterLister)

// NewCSIDriverClusterLister returns a new CSIDriverClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewCSIDriverClusterLister(indexer cache.Indexer) CSIDriverClusterLister {
	return &cSIDriverClusterLister{
		kcplisters.NewCluster[*storagev1beta1.CSIDriver](indexer, storagev1beta1.Resource("csidriver")),
	}
}

// Cluster scopes the lister to one workspace, allowing users to list and get CSIDrivers.
func (l *cSIDriverClusterLister) Cluster(clusterName logicalcluster.Name) listersstoragev1beta1.CSIDriverLister {
	return &cSIDriverLister{
		l.ResourceClusterIndexer.WithCluster(clusterName),
	}
}

// cSIDriverLister can list all CSIDrivers inside a workspace
// or scope down to a listersstoragev1beta1.CSIDriverNamespaceLister for one namespace.
type cSIDriverLister struct {
	kcplisters.ResourceIndexer[*storagev1beta1.CSIDriver]
}

var _ listersstoragev1beta1.CSIDriverLister = new(cSIDriverLister)

// NewCSIDriverLister returns a new CSIDriverLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewCSIDriverLister(indexer cache.Indexer) listersstoragev1beta1.CSIDriverLister {
	return &cSIDriverLister{
		kcplisters.New[*storagev1beta1.CSIDriver](indexer, storagev1beta1.Resource("csidriver")),
	}
}

// cSIDriverScopedLister can list all CSIDrivers inside a workspace
// or scope down to a listersstoragev1beta1.CSIDriverNamespaceLister.
type cSIDriverScopedLister struct {
	kcplisters.ResourceIndexer[*storagev1beta1.CSIDriver]
}
