apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v231029-3858785a2.workspaceproxies.proxy.kcp.io
spec:
  group: proxy.kcp.io
  names:
    categories:
    - kcp
    kind: WorkspaceProxy
    listKind: WorkspaceProxyList
    plural: workspaceproxies
    singular: workspaceproxy
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      description: WorkspaceProxy describes the current WorkspaceProxy.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceProxySpec is the specification of the Cluster proxy
            resource.
          properties:
            type:
              type: string
          type: object
        status:
          description: WorkspaceProxyStatus communicates the observed state of the
            Workspace proxy.
          properties:
            URL:
              description: url is the address under which the Kubernetes-cluster-like
                endpoint can be found. This URL can be used to access the cluster
                with standard Kubernetes client libraries and command line tools via
                proxy.
              type: string
            conditions:
              description: Current processing state of the Cluster proxy.
              items:
                description: Condition defines an observation of a object operational
                  state.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another. This should be when the underlying condition changed.
                      If that is not known, then using the time when the API field
                      changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition. This field may be empty.
                    type: string
                  reason:
                    description: The reason for the condition's last transition in
                      CamelCase. The specific API may choose whether or not this field
                      is considered a guaranteed API. This field may not be empty.
                    type: string
                  severity:
                    description: Severity provides an explicit classification of Reason
                      code, so the users or machines can immediately understand the
                      current situation and act accordingly. The Severity field MUST
                      be set only when Status=False.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources
                      like Available, but because arbitrary conditions can be useful
                      (see .node.status.conditions), the ability to deconflict is
                      important.
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
            lastProxyHeartbeatTime:
              description: A timestamp indicating when the proxy last reported status.
              format: date-time
              type: string
            phase:
              default: Scheduling
              description: Phase of the cluster proxy (Initializing, Ready).
              enum:
              - Scheduling
              - Initializing
              - Ready
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
