apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Name
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ConfigMapName
    verbs:
      - "get"
      - "list"
      - "watch"
