
# Adds namespace to all resources.
namespace: kcp

resources:
- ./component_namespace.yaml
- ./service_account.yaml
- ./clusterrole_binding.yaml
- ./deployment.yaml

secretGenerator:
  - name: syncer-kubeconfig-secret
    namespace: kcp
    files:
      - kubeconfig=syncer-kubeconfig
    type: "Opaque"

generatorOptions:
  disableNameSuffixHash: true