apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: kube-bind.io
spec:
  latestResourceSchemas:
  - v241216-832011705.apiservicebindings.kube-bind.io
  - v241216-832011705.apiserviceexportrequests.kube-bind.io
  - v241216-832011705.apiserviceexports.kube-bind.io
  - v241216-832011705.apiservicenamespaces.kube-bind.io
  - v241216-832011705.clusterbindings.kube-bind.io
status: {}
