---
# Root etcd CA certificate for all etcd components across all kcp deployment.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-ca
  namespace: kcp-zheng
spec:
  secretName: etcd-ca-tls
  isCA: true
  commonName: etcd-ca
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
---
# etcd Peer CA certificate (for peer communication)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer-ca
  namespace: kcp-zheng
spec:
  secretName: etcd-peer-ca-tls
  isCA: true
  commonName: etcd-peer-ca
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
---
# etcd Peer CA issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-peer-ca
  namespace: kcp-zheng
spec:
  ca:
    secretName: etcd-peer-ca-tls
---
# etcd server certificate (for client connections)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server-tls
  namespace: kcp-zheng
spec:
  secretName: etcd-server-tls
  commonName: etcd-server
  dnsNames:
  - root-local
  - root-client
  - root-client.kcp-zheng
  - root-client.kcp-zheng.svc
  - root-client.kcp-zheng.svc.cluster.local
  - "*.root-peer"
  - "*.root-peer.kcp-zheng"
  - "*.root-peer.kcp-zheng.svc"
  - "*.root-peer.kcp-zheng.svc.cluster.local"
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
---
# etcd client certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client-tls
  namespace: kcp-zheng
spec:
  secretName: etcd-client-tls
  commonName: etcd-client
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
---
# etcd peer certificate (for etcd member communication)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer-tls
  namespace: kcp-zheng
spec:
  secretName: etcd-peer-tls
  commonName: etcd-peer
  dnsNames:
  - root-peer
  - root-peer.kcp-zheng
  - root-peer.kcp-zheng.svc
  - root-peer.kcp-zheng.svc.cluster.local
  - "*.root-peer"
  - "*.root-peer.kcp-zheng"
  - "*.root-peer.kcp-zheng.svc"
  - "*.root-peer.kcp-zheng.svc.cluster.local"
  issuerRef:
    name: etcd-peer-ca
    kind: Issuer
---
# etcd backup-restore server certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-backup-restore-server-tls
  namespace: kcp-zheng
spec:
  secretName: etcd-backup-restore-server-tls
  commonName: etcd-backup-restore-server
  dnsNames:
  - root-local
  - localhost
  - 127.0.0.1
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer
---
# etcd backup-restore client certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-backup-restore-client-tls
  namespace: kcp-zheng
spec:
  secretName: etcd-backup-restore-client-tls
  commonName: etcd-backup-restore-client
  issuerRef:
    name: etcd-ca
    kind: ClusterIssuer