//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/kcp-dev/sdk/apis/third_party/conditions/apis/conditions/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBinding) DeepCopyInto(out *APIBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBinding.
func (in *APIBinding) DeepCopy() *APIBinding {
	if in == nil {
		return nil
	}
	out := new(APIBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBindingList) DeepCopyInto(out *APIBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBindingList.
func (in *APIBindingList) DeepCopy() *APIBindingList {
	if in == nil {
		return nil
	}
	out := new(APIBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBindingSpec) DeepCopyInto(out *APIBindingSpec) {
	*out = *in
	in.Reference.DeepCopyInto(&out.Reference)
	if in.PermissionClaims != nil {
		in, out := &in.PermissionClaims, &out.PermissionClaims
		*out = make([]AcceptablePermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBindingSpec.
func (in *APIBindingSpec) DeepCopy() *APIBindingSpec {
	if in == nil {
		return nil
	}
	out := new(APIBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIBindingStatus) DeepCopyInto(out *APIBindingStatus) {
	*out = *in
	if in.BoundResources != nil {
		in, out := &in.BoundResources, &out.BoundResources
		*out = make([]BoundAPIResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedPermissionClaims != nil {
		in, out := &in.AppliedPermissionClaims, &out.AppliedPermissionClaims
		*out = make([]ScopedPermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportPermissionClaims != nil {
		in, out := &in.ExportPermissionClaims, &out.ExportPermissionClaims
		*out = make([]PermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIBindingStatus.
func (in *APIBindingStatus) DeepCopy() *APIBindingStatus {
	if in == nil {
		return nil
	}
	out := new(APIBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExport) DeepCopyInto(out *APIExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExport.
func (in *APIExport) DeepCopy() *APIExport {
	if in == nil {
		return nil
	}
	out := new(APIExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportList) DeepCopyInto(out *APIExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportList.
func (in *APIExportList) DeepCopy() *APIExportList {
	if in == nil {
		return nil
	}
	out := new(APIExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportSpec) DeepCopyInto(out *APIExportSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(Identity)
		(*in).DeepCopyInto(*out)
	}
	if in.MaximalPermissionPolicy != nil {
		in, out := &in.MaximalPermissionPolicy, &out.MaximalPermissionPolicy
		*out = new(MaximalPermissionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PermissionClaims != nil {
		in, out := &in.PermissionClaims, &out.PermissionClaims
		*out = make([]PermissionClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportSpec.
func (in *APIExportSpec) DeepCopy() *APIExportSpec {
	if in == nil {
		return nil
	}
	out := new(APIExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportStatus) DeepCopyInto(out *APIExportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VirtualWorkspaces != nil {
		in, out := &in.VirtualWorkspaces, &out.VirtualWorkspaces
		*out = make([]VirtualWorkspace, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportStatus.
func (in *APIExportStatus) DeepCopy() *APIExportStatus {
	if in == nil {
		return nil
	}
	out := new(APIExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptablePermissionClaim) DeepCopyInto(out *AcceptablePermissionClaim) {
	*out = *in
	in.ScopedPermissionClaim.DeepCopyInto(&out.ScopedPermissionClaim)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptablePermissionClaim.
func (in *AcceptablePermissionClaim) DeepCopy() *AcceptablePermissionClaim {
	if in == nil {
		return nil
	}
	out := new(AcceptablePermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingReference) DeepCopyInto(out *BindingReference) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(ExportBindingReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingReference.
func (in *BindingReference) DeepCopy() *BindingReference {
	if in == nil {
		return nil
	}
	out := new(BindingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundAPIResource) DeepCopyInto(out *BoundAPIResource) {
	*out = *in
	out.Schema = in.Schema
	if in.StorageVersions != nil {
		in, out := &in.StorageVersions, &out.StorageVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundAPIResource.
func (in *BoundAPIResource) DeepCopy() *BoundAPIResource {
	if in == nil {
		return nil
	}
	out := new(BoundAPIResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundAPIResourceSchema) DeepCopyInto(out *BoundAPIResourceSchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundAPIResourceSchema.
func (in *BoundAPIResourceSchema) DeepCopy() *BoundAPIResourceSchema {
	if in == nil {
		return nil
	}
	out := new(BoundAPIResourceSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportBindingReference) DeepCopyInto(out *ExportBindingReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportBindingReference.
func (in *ExportBindingReference) DeepCopy() *ExportBindingReference {
	if in == nil {
		return nil
	}
	out := new(ExportBindingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupResource) DeepCopyInto(out *GroupResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupResource.
func (in *GroupResource) DeepCopy() *GroupResource {
	if in == nil {
		return nil
	}
	out := new(GroupResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identity) DeepCopyInto(out *Identity) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in *Identity) DeepCopy() *Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalAPIExportPolicy) DeepCopyInto(out *LocalAPIExportPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalAPIExportPolicy.
func (in *LocalAPIExportPolicy) DeepCopy() *LocalAPIExportPolicy {
	if in == nil {
		return nil
	}
	out := new(LocalAPIExportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximalPermissionPolicy) DeepCopyInto(out *MaximalPermissionPolicy) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalAPIExportPolicy)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximalPermissionPolicy.
func (in *MaximalPermissionPolicy) DeepCopy() *MaximalPermissionPolicy {
	if in == nil {
		return nil
	}
	out := new(MaximalPermissionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionClaim) DeepCopyInto(out *PermissionClaim) {
	*out = *in
	out.GroupResource = in.GroupResource
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionClaim.
func (in *PermissionClaim) DeepCopy() *PermissionClaim {
	if in == nil {
		return nil
	}
	out := new(PermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionClaimSelector) DeepCopyInto(out *PermissionClaimSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionClaimSelector.
func (in *PermissionClaimSelector) DeepCopy() *PermissionClaimSelector {
	if in == nil {
		return nil
	}
	out := new(PermissionClaimSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSchema) DeepCopyInto(out *ResourceSchema) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSchema.
func (in *ResourceSchema) DeepCopy() *ResourceSchema {
	if in == nil {
		return nil
	}
	out := new(ResourceSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSchemaStorage) DeepCopyInto(out *ResourceSchemaStorage) {
	*out = *in
	if in.CRD != nil {
		in, out := &in.CRD, &out.CRD
		*out = new(ResourceSchemaStorageCRD)
		**out = **in
	}
	if in.Virtual != nil {
		in, out := &in.Virtual, &out.Virtual
		*out = new(ResourceSchemaStorageVirtual)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSchemaStorage.
func (in *ResourceSchemaStorage) DeepCopy() *ResourceSchemaStorage {
	if in == nil {
		return nil
	}
	out := new(ResourceSchemaStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSchemaStorageCRD) DeepCopyInto(out *ResourceSchemaStorageCRD) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSchemaStorageCRD.
func (in *ResourceSchemaStorageCRD) DeepCopy() *ResourceSchemaStorageCRD {
	if in == nil {
		return nil
	}
	out := new(ResourceSchemaStorageCRD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSchemaStorageVirtual) DeepCopyInto(out *ResourceSchemaStorageVirtual) {
	*out = *in
	in.Reference.DeepCopyInto(&out.Reference)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSchemaStorageVirtual.
func (in *ResourceSchemaStorageVirtual) DeepCopy() *ResourceSchemaStorageVirtual {
	if in == nil {
		return nil
	}
	out := new(ResourceSchemaStorageVirtual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopedPermissionClaim) DeepCopyInto(out *ScopedPermissionClaim) {
	*out = *in
	in.PermissionClaim.DeepCopyInto(&out.PermissionClaim)
	in.Selector.DeepCopyInto(&out.Selector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopedPermissionClaim.
func (in *ScopedPermissionClaim) DeepCopy() *ScopedPermissionClaim {
	if in == nil {
		return nil
	}
	out := new(ScopedPermissionClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualWorkspace) DeepCopyInto(out *VirtualWorkspace) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualWorkspace.
func (in *VirtualWorkspace) DeepCopy() *VirtualWorkspace {
	if in == nil {
		return nil
	}
	out := new(VirtualWorkspace)
	in.DeepCopyInto(out)
	return out
}
