/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	logicalcluster "github.com/kcp-dev/logicalcluster/v3"
	kcpmigrationv1alpha1 "github.com/kcp-dev/sdk/apis/migration/v1alpha1"
	kcpversioned "github.com/kcp-dev/sdk/client/clientset/versioned"
	kcpcluster "github.com/kcp-dev/sdk/client/clientset/versioned/cluster"
	kcpinternalinterfaces "github.com/kcp-dev/sdk/client/informers/externalversions/internalinterfaces"
	kcpv1alpha1 "github.com/kcp-dev/sdk/client/listers/migration/v1alpha1"
)

// APIExportIdentityRotationClusterInformer provides access to a shared informer and lister for
// APIExportIdentityRotations.
type APIExportIdentityRotationClusterInformer interface {
	Cluster(logicalcluster.Name) APIExportIdentityRotationInformer
	ClusterWithContext(context.Context, logicalcluster.Name) APIExportIdentityRotationInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kcpv1alpha1.APIExportIdentityRotationClusterLister
}

type aPIExportIdentityRotationClusterInformer struct {
	factory          kcpinternalinterfaces.SharedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// NewAPIExportIdentityRotationClusterInformer constructs a new informer for APIExportIdentityRotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAPIExportIdentityRotationClusterInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredAPIExportIdentityRotationClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAPIExportIdentityRotationClusterInformer constructs a new informer for APIExportIdentityRotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportIdentityRotationClusterInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrationV1alpha1().APIExportIdentityRotations().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrationV1alpha1().APIExportIdentityRotations().Watch(context.Background(), options)
			},
		}, client),
		&kcpmigrationv1alpha1.APIExportIdentityRotation{},
		resyncPeriod,
		indexers,
	)
}

func (i *aPIExportIdentityRotationClusterInformer) defaultInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredAPIExportIdentityRotationClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,
	}, i.tweakListOptions)
}

func (i *aPIExportIdentityRotationClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return i.factory.InformerFor(&kcpmigrationv1alpha1.APIExportIdentityRotation{}, i.defaultInformer)
}

func (i *aPIExportIdentityRotationClusterInformer) Lister() kcpv1alpha1.APIExportIdentityRotationClusterLister {
	return kcpv1alpha1.NewAPIExportIdentityRotationClusterLister(i.Informer().GetIndexer())
}

func (i *aPIExportIdentityRotationClusterInformer) Cluster(clusterName logicalcluster.Name) APIExportIdentityRotationInformer {
	return &aPIExportIdentityRotationInformer{
		informer: i.Informer().Cluster(clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

func (i *aPIExportIdentityRotationClusterInformer) ClusterWithContext(ctx context.Context, clusterName logicalcluster.Name) APIExportIdentityRotationInformer {
	return &aPIExportIdentityRotationInformer{
		informer: i.Informer().ClusterWithContext(ctx, clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

type aPIExportIdentityRotationInformer struct {
	informer cache.SharedIndexInformer
	lister   kcpv1alpha1.APIExportIdentityRotationLister
}

func (i *aPIExportIdentityRotationInformer) Informer() cache.SharedIndexInformer {
	return i.informer
}

func (i *aPIExportIdentityRotationInformer) Lister() kcpv1alpha1.APIExportIdentityRotationLister {
	return i.lister
}

// APIExportIdentityRotationInformer provides access to a shared informer and lister for
// APIExportIdentityRotations.
type APIExportIdentityRotationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kcpv1alpha1.APIExportIdentityRotationLister
}

type aPIExportIdentityRotationScopedInformer struct {
	factory          kcpinternalinterfaces.SharedScopedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// NewAPIExportIdentityRotationInformer constructs a new informer for APIExportIdentityRotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAPIExportIdentityRotationInformer(client kcpversioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAPIExportIdentityRotationInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAPIExportIdentityRotationInformer constructs a new informer for APIExportIdentityRotation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportIdentityRotationInformer(client kcpversioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrationV1alpha1().APIExportIdentityRotations().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrationV1alpha1().APIExportIdentityRotations().Watch(context.Background(), options)
			},
		}, client),
		&kcpmigrationv1alpha1.APIExportIdentityRotation{},
		resyncPeriod,
		indexers,
	)
}

func (i *aPIExportIdentityRotationScopedInformer) Informer() cache.SharedIndexInformer {
	return i.factory.InformerFor(&kcpmigrationv1alpha1.APIExportIdentityRotation{}, i.defaultInformer)
}

func (i *aPIExportIdentityRotationScopedInformer) Lister() kcpv1alpha1.APIExportIdentityRotationLister {
	return kcpv1alpha1.NewAPIExportIdentityRotationLister(i.Informer().GetIndexer())
}

func (i *aPIExportIdentityRotationScopedInformer) defaultInformer(client kcpversioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAPIExportIdentityRotationInformer(client, resyncPeriod, cache.Indexers{}, i.tweakListOptions)
}
