/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"	
	"github.com/kcp-dev/logicalcluster/v3"
	
	"k8s.io/client-go/tools/cache"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/api/errors"

	cachev1alpha1 "github.com/kcp-dev/kcp/sdk/apis/cache/v1alpha1"
	)

// PublishedObjectClusterLister can list PublishedObjects across all workspaces, or scope down to a PublishedObjectLister for one workspace.
// All objects returned here must be treated as read-only.
type PublishedObjectClusterLister interface {
	// List lists all PublishedObjects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cachev1alpha1.PublishedObject, err error)
	// Cluster returns a lister that can list and get PublishedObjects in one workspace.
Cluster(clusterName logicalcluster.Name) PublishedObjectLister
PublishedObjectClusterListerExpansion
}

type publishedObjectClusterLister struct {
	indexer cache.Indexer
}

// NewPublishedObjectClusterLister returns a new PublishedObjectClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewPublishedObjectClusterLister(indexer cache.Indexer) *publishedObjectClusterLister {
	return &publishedObjectClusterLister{indexer: indexer}
}

// List lists all PublishedObjects in the indexer across all workspaces.
func (s *publishedObjectClusterLister) List(selector labels.Selector) (ret []*cachev1alpha1.PublishedObject, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*cachev1alpha1.PublishedObject))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get PublishedObjects.
func (s *publishedObjectClusterLister) Cluster(clusterName logicalcluster.Name) PublishedObjectLister {
return &publishedObjectLister{indexer: s.indexer, clusterName: clusterName}
}

// PublishedObjectLister can list all PublishedObjects, or get one in particular.
// All objects returned here must be treated as read-only.
type PublishedObjectLister interface {
	// List lists all PublishedObjects in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cachev1alpha1.PublishedObject, err error)
// Get retrieves the PublishedObject from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cachev1alpha1.PublishedObject, error)
PublishedObjectListerExpansion
}
// publishedObjectLister can list all PublishedObjects inside a workspace.
type publishedObjectLister struct {
	indexer cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all PublishedObjects in the indexer for a workspace.
func (s *publishedObjectLister) List(selector labels.Selector) (ret []*cachev1alpha1.PublishedObject, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*cachev1alpha1.PublishedObject))
	})
	return ret, err
}

// Get retrieves the PublishedObject from the indexer for a given workspace and name.
func (s *publishedObjectLister) Get(name string) (*cachev1alpha1.PublishedObject, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(cachev1alpha1.Resource("publishedobjects"), name)
	}
	return obj.(*cachev1alpha1.PublishedObject), nil
}
// NewPublishedObjectLister returns a new PublishedObjectLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewPublishedObjectLister(indexer cache.Indexer) *publishedObjectScopedLister {
	return &publishedObjectScopedLister{indexer: indexer}
}

// publishedObjectScopedLister can list all PublishedObjects inside a workspace.
type publishedObjectScopedLister struct {
	indexer cache.Indexer
}

// List lists all PublishedObjects in the indexer for a workspace.
func (s *publishedObjectScopedLister) List(selector labels.Selector) (ret []*cachev1alpha1.PublishedObject, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*cachev1alpha1.PublishedObject))
	})
	return ret, err
}

// Get retrieves the PublishedObject from the indexer for a given workspace and name.
func (s *publishedObjectScopedLister) Get(name string) (*cachev1alpha1.PublishedObject, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(cachev1alpha1.Resource("publishedobjects"), name)
	}
	return obj.(*cachev1alpha1.PublishedObject), nil
}
