# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:debug
WORKDIR /
COPY --from=kcp-build workspace/bin/syncer /
ENTRYPOINT ["/syncer"]
