# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:debug
WORKDIR /
COPY --from=kcp-build workspace/bin/kcp /
# Use uid of nonroot user (65532) because kubernetes expects numeric user when applying pod security policies
RUN ["/busybox/sh", "-c", "mkdir -p /data && chown 65532:65532 /data"]
USER 65532:65532
WORKDIR /data
VOLUME /data
ENTRYPOINT ["/kcp"]
CMD ["start"]
