apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: proxy
  annotations:
    bootstrap.kcp.io/create-only: "true"
spec:
  type:
    name: universal
    path: root
  location:
    selector:
      matchLabels:
        name: root
