/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/kcp-dev/sdk/apis/core/v1alpha1"
)

// LogicalClusterOwnerUserApplyConfiguration represents a declarative configuration of the LogicalClusterOwnerUser type for use
// with apply.
//
// LogicalClusterOwnerUser holds the identity of the workspace creator.
type LogicalClusterOwnerUserApplyConfiguration struct {
	// username is the username of the user who created the workspace.
	Username *string `json:"username,omitempty"`
	// uid is the UID of the user.
	UID *string `json:"uid,omitempty"`
	// groups are the groups the user belongs to.
	Groups []string `json:"groups,omitempty"`
	// extra contains additional user information.
	Extra map[string]corev1alpha1.ExtraValue `json:"extra,omitempty"`
}

// LogicalClusterOwnerUserApplyConfiguration constructs a declarative configuration of the LogicalClusterOwnerUser type for use with
// apply.
func LogicalClusterOwnerUser() *LogicalClusterOwnerUserApplyConfiguration {
	return &LogicalClusterOwnerUserApplyConfiguration{}
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *LogicalClusterOwnerUserApplyConfiguration) WithUsername(value string) *LogicalClusterOwnerUserApplyConfiguration {
	b.Username = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *LogicalClusterOwnerUserApplyConfiguration) WithUID(value string) *LogicalClusterOwnerUserApplyConfiguration {
	b.UID = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *LogicalClusterOwnerUserApplyConfiguration) WithGroups(values ...string) *LogicalClusterOwnerUserApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithExtra puts the entries into the Extra field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extra field,
// overwriting an existing map entries in Extra field with the same key.
func (b *LogicalClusterOwnerUserApplyConfiguration) WithExtra(entries map[string]corev1alpha1.ExtraValue) *LogicalClusterOwnerUserApplyConfiguration {
	if b.Extra == nil && len(entries) > 0 {
		b.Extra = make(map[string]corev1alpha1.ExtraValue, len(entries))
	}
	for k, v := range entries {
		b.Extra[k] = v
	}
	return b
}
