---
apiVersion: v1
kind: Namespace
metadata:
  name: kcp-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: kcp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - services
  - deployments
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syncer
subjects:
- kind: ServiceAccount
  name: syncer
  namespace: kcp-system
---
apiVersion: v1
kind: Secret
metadata:
  name: syncer-kcp-sa
  namespace: kcp-system
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: default-cluster
      cluster:
        certificate-authority-data: KCP_SYNCER_CACRT
        server: KCP_SERVER_URL
    contexts:
    - name: default-context
      context:
        cluster: default-cluster
        namespace: default
        user: default-user
    current-context: default-context
    users:
    - name: default-user
      user:
        token: KCP_SYNCER_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kcp-syncer-ID
  name: syncer
  namespace: kcp-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kcp-syncer-ID
  template:
    metadata:
      labels:
        app: kcp-syncer-ID
    spec:
      containers:
      - command:
        - /ko-app/syncer
        args:
        - --from-kubeconfig=/kcp/config/kubeconfig
        - --workload-cluster-name=WORKLOAD_CLUSTER_NAME   # ID of the -to cluster. Resources with this ID set in the 'workloads.kcp.dev/cluster' label will be synced
        - --from-cluster=KCP_LOGICAL_CLUSTER_NAME         # Name of the -from logical cluster
        - --sync-resources=deployments.apps               # List of resources to be synchronized in kcp
        - --sync-resources=ingresses.networking.k8s
        - --sync-resources=services
        image: ghcr.io/kcp-dev/kcp/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:7005a96@sha256:9735cbe04f4a5c7137e1f544fa29520f1624304629371d6bd185fcfe15f3b7af
        imagePullPolicy: IfNotPresent
        name: syncer
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: kcp-kubeconfig
          mountPath: /kcp/config
          readOnly: true
        env:
        - name: SYNCER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: syncer
      volumes:
        - name: kcp-kubeconfig
          configMap:
            name: syncer-kcp-config
            optional: false
