/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// APIExportSpecApplyConfiguration represents a declarative configuration of the APIExportSpec type for use
// with apply.
//
// APIExportSpec defines the desired state of APIExport.
type APIExportSpecApplyConfiguration struct {
	// latestResourceSchemas records the latest APIResourceSchemas that are exposed
	// with this APIExport.
	//
	// The schemas can be changed in the life-cycle of the APIExport. These changes
	// have no effect on existing APIBindings, but only on newly bound ones.
	//
	// For updating existing APIBindings, use an APIDeployment keeping bound
	// workspaces up-to-date.
	LatestResourceSchemas []string `json:"latestResourceSchemas,omitempty"`
	// identity points to a secret that contains the API identity in the 'key' file.
	// The API identity determines an unique etcd prefix for objects stored via this
	// APIExport.
	//
	// Different APIExport in a workspace can share a common identity, or have different
	// ones. The identity (the secret) can also be transferred to another workspace
	// when the APIExport is moved.
	//
	// The identity is a secret of the API provider. The APIBindings referencing this APIExport
	// will store a derived, non-sensitive value of this identity.
	//
	// The identity of an APIExport cannot be changed. A derived, non-sensitive value of
	// the identity key is stored in the APIExport status and this value is immutable.
	//
	// The identity is defaulted. A secret with the name of the APIExport is automatically
	// created.
	Identity *IdentityApplyConfiguration `json:"identity,omitempty"`
	// maximalPermissionPolicy will allow for a service provider to set an upper bound on what is allowed
	// for a consumer of this API. If the policy is not set, no upper bound is applied,
	// i.e the consuming users can do whatever the user workspace allows the user to do.
	//
	// The policy consists of RBAC (Cluster)Roles and (Cluster)Bindings. A request of a user in
	// a workspace that binds to this APIExport via an APIBinding is additionally checked against
	// these rules, with the user name and the groups prefixed with `apis.kcp.io:binding:`.
	//
	// For example: assume a user `adam` with groups `system:authenticated` and `a-team` binds to
	// this APIExport in another workspace root:org:ws. Then a request in that workspace
	// against a resource of this APIExport is authorized as every other request in that workspace,
	// but in addition the RBAC policy here in the APIExport workspace has to grant access to the
	// user `apis.kcp.io:binding:adam` with the groups `apis.kcp.io:binding:system:authenticated`
	// and `apis.kcp.io:binding:a-team`.
	//
	// If an APIExport with a maximalPermissionPolicy is deleted, these additional checks will no longer
	// be applied to resources of this APIExport.
	//
	// For example: Assume an APIExport with a maximalPermissionPolicy that only allows creation and
	// deletion of resources, but not updates - if the APIExport is deleted users will be able to update
	// the resources of the APIExport again (given the constraints of their workspace's RBAC policies).
	MaximalPermissionPolicy *MaximalPermissionPolicyApplyConfiguration `json:"maximalPermissionPolicy,omitempty"`
	// permissionClaims make resources available in APIExport's virtual workspace that are not part
	// of the actual APIExport resources.
	//
	// PermissionClaims are optional and should be the least access necessary to complete the functions
	// that the service provider needs. Access is asked for on a GroupResource + identity basis.
	//
	// PermissionClaims must be accepted by the user's explicit acknowledgement. Hence, when claims
	// change, the respecting objects are not visible immediately.
	//
	// PermissionClaims overlapping with the APIExport resources are ignored.
	PermissionClaims []PermissionClaimApplyConfiguration `json:"permissionClaims,omitempty"`
}

// APIExportSpecApplyConfiguration constructs a declarative configuration of the APIExportSpec type for use with
// apply.
func APIExportSpec() *APIExportSpecApplyConfiguration {
	return &APIExportSpecApplyConfiguration{}
}

// WithLatestResourceSchemas adds the given value to the LatestResourceSchemas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LatestResourceSchemas field.
func (b *APIExportSpecApplyConfiguration) WithLatestResourceSchemas(values ...string) *APIExportSpecApplyConfiguration {
	for i := range values {
		b.LatestResourceSchemas = append(b.LatestResourceSchemas, values[i])
	}
	return b
}

// WithIdentity sets the Identity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identity field is set to the value of the last call.
func (b *APIExportSpecApplyConfiguration) WithIdentity(value *IdentityApplyConfiguration) *APIExportSpecApplyConfiguration {
	b.Identity = value
	return b
}

// WithMaximalPermissionPolicy sets the MaximalPermissionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaximalPermissionPolicy field is set to the value of the last call.
func (b *APIExportSpecApplyConfiguration) WithMaximalPermissionPolicy(value *MaximalPermissionPolicyApplyConfiguration) *APIExportSpecApplyConfiguration {
	b.MaximalPermissionPolicy = value
	return b
}

// WithPermissionClaims adds the given value to the PermissionClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PermissionClaims field.
func (b *APIExportSpecApplyConfiguration) WithPermissionClaims(values ...*PermissionClaimApplyConfiguration) *APIExportSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPermissionClaims")
		}
		b.PermissionClaims = append(b.PermissionClaims, *values[i])
	}
	return b
}
