apiVersion: apis.kcp.io/v1alpha2
kind: APIBinding
metadata:
  name: access.kcp.io
spec:
  reference:
    export:
      path: root
      name: access.kcp.io
  permissionClaims:
    - group: rbac.authorization.k8s.io
      resource: clusterrolebindings
      verbs: [get, list, watch]
      state: Accepted
      selector:
        matchAll: true
    - group: rbac.authorization.k8s.io
      resource: rolebindings
      verbs: [get, list, watch]
      state: Accepted
      selector:
        matchAll: true
    - group: rbac.authorization.k8s.io
      resource: clusterroles
      verbs: [get, list, watch]
      state: Accepted
      selector:
        matchAll: true
    - group: rbac.authorization.k8s.io
      resource: roles
      verbs: [get, list, watch]
      state: Accepted
      selector:
        matchAll: true
