/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	appsv1beta2 "k8s.io/api/apps/v1beta2"
	v1beta2 "k8s.io/client-go/applyconfigurations/apps/v1beta2"
	typedappsv1beta2 "k8s.io/client-go/kubernetes/typed/apps/v1beta2"

	typedkcpappsv1beta2 "github.com/kcp-dev/client-go/kubernetes/typed/apps/v1beta2"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// deploymentClusterClient implements DeploymentClusterInterface
type deploymentClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*appsv1beta2.Deployment, *appsv1beta2.DeploymentList]
	Fake *kcptesting.Fake
}

func newFakeDeploymentClusterClient(fake *AppsV1beta2ClusterClient) typedkcpappsv1beta2.DeploymentClusterInterface {
	return &deploymentClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*appsv1beta2.Deployment, *appsv1beta2.DeploymentList](
			fake.Fake,
			appsv1beta2.SchemeGroupVersion.WithResource("deployments"),
			appsv1beta2.SchemeGroupVersion.WithKind("Deployment"),
			func() *appsv1beta2.Deployment { return &appsv1beta2.Deployment{} },
			func() *appsv1beta2.DeploymentList { return &appsv1beta2.DeploymentList{} },
			func(dst, src *appsv1beta2.DeploymentList) { dst.ListMeta = src.ListMeta },
			func(list *appsv1beta2.DeploymentList) []*appsv1beta2.Deployment {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *appsv1beta2.DeploymentList, items []*appsv1beta2.Deployment) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *deploymentClusterClient) Cluster(cluster logicalcluster.Path) typedkcpappsv1beta2.DeploymentsNamespacer {
	return &deploymentNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type deploymentNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *deploymentNamespacer) Namespace(namespace string) typedappsv1beta2.DeploymentInterface {
	return newFakeDeploymentClient(n.Fake, namespace, n.ClusterPath)
}

// deploymentScopedClient implements DeploymentInterface
type deploymentScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*appsv1beta2.Deployment, *appsv1beta2.DeploymentList, *v1beta2.DeploymentApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeDeploymentClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedappsv1beta2.DeploymentInterface {
	return &deploymentScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*appsv1beta2.Deployment, *appsv1beta2.DeploymentList, *v1beta2.DeploymentApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			appsv1beta2.SchemeGroupVersion.WithResource("deployments"),
			appsv1beta2.SchemeGroupVersion.WithKind("Deployment"),
			func() *appsv1beta2.Deployment { return &appsv1beta2.Deployment{} },
			func() *appsv1beta2.DeploymentList { return &appsv1beta2.DeploymentList{} },
			func(dst, src *appsv1beta2.DeploymentList) { dst.ListMeta = src.ListMeta },
			func(list *appsv1beta2.DeploymentList) []*appsv1beta2.Deployment {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *appsv1beta2.DeploymentList, items []*appsv1beta2.Deployment) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
