/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	appsv1beta2 "k8s.io/api/apps/v1beta2"
	v1beta2 "k8s.io/client-go/applyconfigurations/apps/v1beta2"
	typedappsv1beta2 "k8s.io/client-go/kubernetes/typed/apps/v1beta2"

	typedkcpappsv1beta2 "github.com/kcp-dev/client-go/kubernetes/typed/apps/v1beta2"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// replicaSetClusterClient implements ReplicaSetClusterInterface
type replicaSetClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*appsv1beta2.ReplicaSet, *appsv1beta2.ReplicaSetList]
	Fake *kcptesting.Fake
}

func newFakeReplicaSetClusterClient(fake *AppsV1beta2ClusterClient) typedkcpappsv1beta2.ReplicaSetClusterInterface {
	return &replicaSetClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*appsv1beta2.ReplicaSet, *appsv1beta2.ReplicaSetList](
			fake.Fake,
			appsv1beta2.SchemeGroupVersion.WithResource("replicasets"),
			appsv1beta2.SchemeGroupVersion.WithKind("ReplicaSet"),
			func() *appsv1beta2.ReplicaSet { return &appsv1beta2.ReplicaSet{} },
			func() *appsv1beta2.ReplicaSetList { return &appsv1beta2.ReplicaSetList{} },
			func(dst, src *appsv1beta2.ReplicaSetList) { dst.ListMeta = src.ListMeta },
			func(list *appsv1beta2.ReplicaSetList) []*appsv1beta2.ReplicaSet {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *appsv1beta2.ReplicaSetList, items []*appsv1beta2.ReplicaSet) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *replicaSetClusterClient) Cluster(cluster logicalcluster.Path) typedkcpappsv1beta2.ReplicaSetsNamespacer {
	return &replicaSetNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type replicaSetNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *replicaSetNamespacer) Namespace(namespace string) typedappsv1beta2.ReplicaSetInterface {
	return newFakeReplicaSetClient(n.Fake, namespace, n.ClusterPath)
}

// replicaSetScopedClient implements ReplicaSetInterface
type replicaSetScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*appsv1beta2.ReplicaSet, *appsv1beta2.ReplicaSetList, *v1beta2.ReplicaSetApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeReplicaSetClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedappsv1beta2.ReplicaSetInterface {
	return &replicaSetScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*appsv1beta2.ReplicaSet, *appsv1beta2.ReplicaSetList, *v1beta2.ReplicaSetApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			appsv1beta2.SchemeGroupVersion.WithResource("replicasets"),
			appsv1beta2.SchemeGroupVersion.WithKind("ReplicaSet"),
			func() *appsv1beta2.ReplicaSet { return &appsv1beta2.ReplicaSet{} },
			func() *appsv1beta2.ReplicaSetList { return &appsv1beta2.ReplicaSetList{} },
			func(dst, src *appsv1beta2.ReplicaSetList) { dst.ListMeta = src.ListMeta },
			func(list *appsv1beta2.ReplicaSetList) []*appsv1beta2.ReplicaSet {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *appsv1beta2.ReplicaSetList, items []*appsv1beta2.ReplicaSet) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
