//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	tenancyv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tenancy/v1alpha1"
	tenancyv1alpha1client "github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/tenancy/v1alpha1"
)

// ClusterWorkspaceTypesClusterGetter has a method to return a ClusterWorkspaceTypeClusterInterface.
// A group's cluster client should implement this interface.
type ClusterWorkspaceTypesClusterGetter interface {
	ClusterWorkspaceTypes() ClusterWorkspaceTypeClusterInterface
}

// ClusterWorkspaceTypeClusterInterface can operate on ClusterWorkspaceTypes across all clusters,
// or scope down to one cluster and return a tenancyv1alpha1client.ClusterWorkspaceTypeInterface.
type ClusterWorkspaceTypeClusterInterface interface {
	Cluster(logicalcluster.Path) tenancyv1alpha1client.ClusterWorkspaceTypeInterface
	List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.ClusterWorkspaceTypeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type clusterWorkspaceTypesClusterInterface struct {
	clientCache kcpclient.Cache[*tenancyv1alpha1client.TenancyV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *clusterWorkspaceTypesClusterInterface) Cluster(clusterPath logicalcluster.Path) tenancyv1alpha1client.ClusterWorkspaceTypeInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).ClusterWorkspaceTypes()
}

// List returns the entire collection of all ClusterWorkspaceTypes across all clusters.
func (c *clusterWorkspaceTypesClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*tenancyv1alpha1.ClusterWorkspaceTypeList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterWorkspaceTypes().List(ctx, opts)
}

// Watch begins to watch all ClusterWorkspaceTypes across all clusters.
func (c *clusterWorkspaceTypesClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterWorkspaceTypes().Watch(ctx, opts)
}
