/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	rbacv1 "k8s.io/api/rbac/v1"
	v1 "k8s.io/client-go/applyconfigurations/rbac/v1"
	typedrbacv1 "k8s.io/client-go/kubernetes/typed/rbac/v1"

	typedkcprbacv1 "github.com/kcp-dev/client-go/kubernetes/typed/rbac/v1"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// clusterRoleClusterClient implements ClusterRoleClusterInterface
type clusterRoleClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList]
	Fake *kcptesting.Fake
}

func newFakeClusterRoleClusterClient(fake *RbacV1ClusterClient) typedkcprbacv1.ClusterRoleClusterInterface {
	return &clusterRoleClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList](
			fake.Fake,
			rbacv1.SchemeGroupVersion.WithResource("clusterroles"),
			rbacv1.SchemeGroupVersion.WithKind("ClusterRole"),
			func() *rbacv1.ClusterRole { return &rbacv1.ClusterRole{} },
			func() *rbacv1.ClusterRoleList { return &rbacv1.ClusterRoleList{} },
			func(dst, src *rbacv1.ClusterRoleList) { dst.ListMeta = src.ListMeta },
			func(list *rbacv1.ClusterRoleList) []*rbacv1.ClusterRole { return kcpgentype.ToPointerSlice(list.Items) },
			func(list *rbacv1.ClusterRoleList, items []*rbacv1.ClusterRole) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *clusterRoleClusterClient) Cluster(cluster logicalcluster.Path) typedrbacv1.ClusterRoleInterface {
	return newFakeClusterRoleClient(c.Fake, cluster)
}

// clusterRoleScopedClient implements ClusterRoleInterface
type clusterRoleScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList, *v1.ClusterRoleApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeClusterRoleClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedrbacv1.ClusterRoleInterface {
	return &clusterRoleScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*rbacv1.ClusterRole, *rbacv1.ClusterRoleList, *v1.ClusterRoleApplyConfiguration](
			fake,
			clusterPath,
			"",
			rbacv1.SchemeGroupVersion.WithResource("clusterroles"),
			rbacv1.SchemeGroupVersion.WithKind("ClusterRole"),
			func() *rbacv1.ClusterRole { return &rbacv1.ClusterRole{} },
			func() *rbacv1.ClusterRoleList { return &rbacv1.ClusterRoleList{} },
			func(dst, src *rbacv1.ClusterRoleList) { dst.ListMeta = src.ListMeta },
			func(list *rbacv1.ClusterRoleList) []*rbacv1.ClusterRole { return kcpgentype.ToPointerSlice(list.Items) },
			func(list *rbacv1.ClusterRoleList, items []*rbacv1.ClusterRole) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
