/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	rbacv1 "k8s.io/api/rbac/v1"
	v1 "k8s.io/client-go/applyconfigurations/rbac/v1"
	typedrbacv1 "k8s.io/client-go/kubernetes/typed/rbac/v1"

	typedkcprbacv1 "github.com/kcp-dev/client-go/kubernetes/typed/rbac/v1"
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
)

// clusterRoleBindingClusterClient implements ClusterRoleBindingClusterInterface
type clusterRoleBindingClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*rbacv1.ClusterRoleBinding, *rbacv1.ClusterRoleBindingList]
	Fake *kcptesting.Fake
}

func newFakeClusterRoleBindingClusterClient(fake *RbacV1ClusterClient) typedkcprbacv1.ClusterRoleBindingClusterInterface {
	return &clusterRoleBindingClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*rbacv1.ClusterRoleBinding, *rbacv1.ClusterRoleBindingList](
			fake.Fake,
			rbacv1.SchemeGroupVersion.WithResource("clusterrolebindings"),
			rbacv1.SchemeGroupVersion.WithKind("ClusterRoleBinding"),
			func() *rbacv1.ClusterRoleBinding { return &rbacv1.ClusterRoleBinding{} },
			func() *rbacv1.ClusterRoleBindingList { return &rbacv1.ClusterRoleBindingList{} },
			func(dst, src *rbacv1.ClusterRoleBindingList) { dst.ListMeta = src.ListMeta },
			func(list *rbacv1.ClusterRoleBindingList) []*rbacv1.ClusterRoleBinding {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *rbacv1.ClusterRoleBindingList, items []*rbacv1.ClusterRoleBinding) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *clusterRoleBindingClusterClient) Cluster(cluster logicalcluster.Path) typedrbacv1.ClusterRoleBindingInterface {
	return newFakeClusterRoleBindingClient(c.Fake, cluster)
}

// clusterRoleBindingScopedClient implements ClusterRoleBindingInterface
type clusterRoleBindingScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*rbacv1.ClusterRoleBinding, *rbacv1.ClusterRoleBindingList, *v1.ClusterRoleBindingApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeClusterRoleBindingClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedrbacv1.ClusterRoleBindingInterface {
	return &clusterRoleBindingScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*rbacv1.ClusterRoleBinding, *rbacv1.ClusterRoleBindingList, *v1.ClusterRoleBindingApplyConfiguration](
			fake,
			clusterPath,
			"",
			rbacv1.SchemeGroupVersion.WithResource("clusterrolebindings"),
			rbacv1.SchemeGroupVersion.WithKind("ClusterRoleBinding"),
			func() *rbacv1.ClusterRoleBinding { return &rbacv1.ClusterRoleBinding{} },
			func() *rbacv1.ClusterRoleBindingList { return &rbacv1.ClusterRoleBindingList{} },
			func(dst, src *rbacv1.ClusterRoleBindingList) { dst.ListMeta = src.ListMeta },
			func(list *rbacv1.ClusterRoleBindingList) []*rbacv1.ClusterRoleBinding {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *rbacv1.ClusterRoleBindingList, items []*rbacv1.ClusterRoleBinding) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
