apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-user
rules:
  - apiGroups: ["tenancy.kcp.io"]
    resources: ["workspaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-viewer
subjects:
  - kind: User
    name: "bob"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-workspace-user
subjects:
  - kind: User
    name: "bob"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: workspace-user
  apiGroup: rbac.authorization.k8s.io
