apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:apiexport:migration:get
rules:
- apiGroups: ["apis.kcp.io"]
  resources:
  - "apiexports"
  resourceNames:
  - "migration.kcp.io"
  verbs: ["get"]
