/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	kcpcachev1alpha1 "github.com/kcp-dev/kcp/sdk/apis/cache/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/cache/v1alpha1"
)

// PublishedObjectsClusterGetter has a method to return a PublishedObjectClusterInterface.
// A group's cluster client should implement this interface.
type PublishedObjectsClusterGetter interface {
	PublishedObjects() PublishedObjectClusterInterface
}

// PublishedObjectClusterInterface can operate on PublishedObjects across all clusters,
// or scope down to one cluster and return a kcpv1alpha1.PublishedObjectInterface.
type PublishedObjectClusterInterface interface {
	Cluster(logicalcluster.Path) kcpv1alpha1.PublishedObjectInterface
	List(ctx context.Context, opts v1.ListOptions) (*kcpcachev1alpha1.PublishedObjectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PublishedObjectClusterExpansion
}

type publishedObjectsClusterInterface struct {
	clientCache kcpclient.Cache[*kcpv1alpha1.CacheV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *publishedObjectsClusterInterface) Cluster(clusterPath logicalcluster.Path) kcpv1alpha1.PublishedObjectInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).PublishedObjects()
}

// List returns the entire collection of all PublishedObjects across all clusters.
func (c *publishedObjectsClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*kcpcachev1alpha1.PublishedObjectList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).PublishedObjects().List(ctx, opts)
}

// Watch begins to watch all PublishedObjects across all clusters.
func (c *publishedObjectsClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).PublishedObjects().Watch(ctx, opts)
}
