FROM squidfunk/mkdocs-material
RUN pip install mkdocs-awesome-pages-plugin mkdocs-macros-plugin mike
ENTRYPOINT []
CMD []
RUN git config --global user.name kcp-docs-bot; \
    git config --global user.email no-reply@kcp.io
