---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  namespace: oidc
spec:
  type: LoadBalancer
  selector:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
