/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kcp-dev/logicalcluster/v3"

	storagemigrationv1alpha1 "k8s.io/api/storagemigration/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	listersstoragemigrationv1alpha1 "k8s.io/client-go/listers/storagemigration/v1alpha1"
	"k8s.io/client-go/tools/cache"

	kcplisters "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/listers"
)

// StorageVersionMigrationClusterLister helps list StorageVersionMigrations across all workspaces,
// or scope down to a StorageVersionMigrationLister for one workspace.
// All objects returned here must be treated as read-only.
type StorageVersionMigrationClusterLister interface {
	// List lists all StorageVersionMigrations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagemigrationv1alpha1.StorageVersionMigration, err error)
	// Cluster returns a lister that can list and get StorageVersionMigrations in one workspace.
	Cluster(clusterName logicalcluster.Name) listersstoragemigrationv1alpha1.StorageVersionMigrationLister
	StorageVersionMigrationClusterListerExpansion
}

// storageVersionMigrationClusterLister implements the StorageVersionMigrationClusterLister interface.
type storageVersionMigrationClusterLister struct {
	kcplisters.ResourceClusterIndexer[*storagemigrationv1alpha1.StorageVersionMigration]
}

var _ StorageVersionMigrationClusterLister = new(storageVersionMigrationClusterLister)

// NewStorageVersionMigrationClusterLister returns a new StorageVersionMigrationClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewStorageVersionMigrationClusterLister(indexer cache.Indexer) StorageVersionMigrationClusterLister {
	return &storageVersionMigrationClusterLister{
		kcplisters.NewCluster[*storagemigrationv1alpha1.StorageVersionMigration](indexer, storagemigrationv1alpha1.Resource("storageversionmigration")),
	}
}

// Cluster scopes the lister to one workspace, allowing users to list and get StorageVersionMigrations.
func (l *storageVersionMigrationClusterLister) Cluster(clusterName logicalcluster.Name) listersstoragemigrationv1alpha1.StorageVersionMigrationLister {
	return &storageVersionMigrationLister{
		l.ResourceClusterIndexer.WithCluster(clusterName),
	}
}

// storageVersionMigrationLister can list all StorageVersionMigrations inside a workspace
// or scope down to a listersstoragemigrationv1alpha1.StorageVersionMigrationNamespaceLister for one namespace.
type storageVersionMigrationLister struct {
	kcplisters.ResourceIndexer[*storagemigrationv1alpha1.StorageVersionMigration]
}

var _ listersstoragemigrationv1alpha1.StorageVersionMigrationLister = new(storageVersionMigrationLister)

// NewStorageVersionMigrationLister returns a new StorageVersionMigrationLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewStorageVersionMigrationLister(indexer cache.Indexer) listersstoragemigrationv1alpha1.StorageVersionMigrationLister {
	return &storageVersionMigrationLister{
		kcplisters.New[*storagemigrationv1alpha1.StorageVersionMigration](indexer, storagemigrationv1alpha1.Resource("storageversionmigration")),
	}
}

// storageVersionMigrationScopedLister can list all StorageVersionMigrations inside a workspace
// or scope down to a listersstoragemigrationv1alpha1.StorageVersionMigrationNamespaceLister.
type storageVersionMigrationScopedLister struct {
	kcplisters.ResourceIndexer[*storagemigrationv1alpha1.StorageVersionMigration]
}
