name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    environment: projects
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # tag=v2.0.0
        with:
          project-url: https://github.com/orgs/kcp-dev/projects/1
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
