name: Documentation

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
  # Pushes to branches do the full build + deployment
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "cmd/**"
      - "docs/**"
      - "pkg/**"
      - ".github/workflows/docs-gen-and-push.yaml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  generate-and-push:
    name: Generate and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0

      - run: git fetch origin gh-pages
      - run: git fetch origin '+refs/tags/v*:refs/tags/v*' --no-tags

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # tag=v6.5.0
        with:
          go-version: v1.26.4
          cache: true

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #tag=v6.3.0
        with:
          python-version: "3.10"
          cache: "pip"

      # mike does not support giving CLI flags for mkdocs, but we also do not
      # want to permanently enable strict mode, so here we enable it just for this
      # task
      - run: |
          echo "strict: true" >> docs/mkdocs.yml

      - run: make generate-cli-docs generate-api-docs deploy-docs
