/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	cachev1alpha1 "github.com/kcp-dev/kcp/sdk/apis/cache/v1alpha1"
	cachev1alpha1listers "github.com/kcp-dev/kcp/sdk/client/listers/cache/v1alpha1"
	clientset "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/cluster"
	scopedclientset "github.com/kcp-dev/kcp/sdk/client/clientset/versioned"
	"github.com/kcp-dev/kcp/sdk/client/informers/externalversions/internalinterfaces"
)

// PublishedObjectClusterInformer provides access to a shared informer and lister for
// PublishedObjects.
type PublishedObjectClusterInformer interface {
	Cluster(logicalcluster.Name) PublishedObjectInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() cachev1alpha1listers.PublishedObjectClusterLister
}

type publishedObjectClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPublishedObjectClusterInformer constructs a new informer for PublishedObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPublishedObjectClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredPublishedObjectClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPublishedObjectClusterInformer constructs a new informer for PublishedObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPublishedObjectClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().PublishedObjects().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().PublishedObjects().Watch(context.TODO(), options)
			},
		},
		&cachev1alpha1.PublishedObject{},
		resyncPeriod,
		indexers,
	)
}

func (f *publishedObjectClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredPublishedObjectClusterInformer(client, resyncPeriod, cache.Indexers{
			kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
			}, 
		f.tweakListOptions,
	)
}

func (f *publishedObjectClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&cachev1alpha1.PublishedObject{}, f.defaultInformer)
}

func (f *publishedObjectClusterInformer) Lister() cachev1alpha1listers.PublishedObjectClusterLister {
	return cachev1alpha1listers.NewPublishedObjectClusterLister(f.Informer().GetIndexer())
}


// PublishedObjectInformer provides access to a shared informer and lister for
// PublishedObjects.
type PublishedObjectInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cachev1alpha1listers.PublishedObjectLister
}
func (f *publishedObjectClusterInformer) Cluster(clusterName logicalcluster.Name) PublishedObjectInformer {
	return &publishedObjectInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type publishedObjectInformer struct {
	informer cache.SharedIndexInformer
	lister cachev1alpha1listers.PublishedObjectLister
}

func (f *publishedObjectInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *publishedObjectInformer) Lister() cachev1alpha1listers.PublishedObjectLister {
	return f.lister
}

type publishedObjectScopedInformer struct {
	factory internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	}

func (f *publishedObjectScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cachev1alpha1.PublishedObject{}, f.defaultInformer)
}

func (f *publishedObjectScopedInformer) Lister() cachev1alpha1listers.PublishedObjectLister {
	return cachev1alpha1listers.NewPublishedObjectLister(f.Informer().GetIndexer())
}

// NewPublishedObjectInformer constructs a new informer for PublishedObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPublishedObjectInformer(client scopedclientset.Interface, resyncPeriod time.Duration,indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPublishedObjectInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPublishedObjectInformer constructs a new informer for PublishedObject type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPublishedObjectInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().PublishedObjects().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().PublishedObjects().Watch(context.TODO(), options)
			},
		},
		&cachev1alpha1.PublishedObject{},
		resyncPeriod,
		indexers,
	)
}

func (f *publishedObjectScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPublishedObjectInformer(client, resyncPeriod,cache.Indexers{ }, f.tweakListOptions)
}

