apiVersion: operator.kcp.io/v1alpha1
kind: Shard
metadata:
  name: alpha
  namespace: kcp-dekker
spec:
  auth:
    serviceAccount:
      enabled: true
    oidc:
      issuerURL: https://auth.example.com
      clientID: platform-mesh
      groupsClaim: groups
      usernameClaim: email
      usernamePrefix: "oidc:"
      groupsPrefix: "oidc:"
      clientSecret: Z2Fyc2lha2FsYmlzdmFuZGVuekWplCg==
  etcd:
    endpoints:
      - https://alpha-client.kcp-dekker.svc.cluster.local:2379
    tlsConfig:
      secretRef:
        name: etcd-ca-tls
  rootShard:
    ref:
      name: root